import { db } from '@/db';
import { clients } from '@/db/schema';

async function main() {
    const sampleClients = [
        {
            name: 'Infosys Technologies',
            email: 'contact@infosys.com',
            phone: '+91-80-2852-0261',
            address: 'Electronics City, Hosur Road, Bangalore, Karnataka 560100',
            industry: 'IT',
            companySize: '500+',
            annualRevenue: 450000000,
            website: 'https://www.infosys.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: 2,
            createdAt: new Date('2023-08-15').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Apollo Hospitals Enterprise',
            email: 'corporate@apollohospitals.com',
            phone: '+91-44-2829-3333',
            address: '21 Greams Lane, Off Greams Road, Chennai, Tamil Nadu 600006',
            industry: 'Healthcare',
            companySize: '500+',
            annualRevenue: 380000000,
            website: 'https://www.apollohospitals.com',
            assignedAccountManager: 2,
            status: 'active',
            leadId: null,
            createdAt: new Date('2023-09-10').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'HDFC Bank Solutions',
            email: 'business@hdfcbank.com',
            phone: '+91-22-6171-6001',
            address: 'HDFC Bank House, Senapati Bapat Marg, Lower Parel, Mumbai, Maharashtra 400013',
            industry: 'Finance',
            companySize: '500+',
            annualRevenue: 500000000,
            website: 'https://www.hdfcbank.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: 5,
            createdAt: new Date('2023-07-22').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'BigBasket Retail',
            email: 'enterprise@bigbasket.com',
            phone: '+91-80-4615-0000',
            address: 'Innovative Retail Concepts Pvt Ltd, 3rd Floor, Brigade Gateway Campus, Bangalore, Karnataka 560026',
            industry: 'Retail',
            companySize: '201-500',
            annualRevenue: 125000000,
            website: 'https://www.bigbasket.com',
            assignedAccountManager: 3,
            status: 'active',
            leadId: 8,
            createdAt: new Date('2023-10-05').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Tata Steel Manufacturing',
            email: 'corporate@tatasteel.com',
            phone: '+91-657-234-9500',
            address: 'Tata Steel Limited, Jamshedpur Works, Jamshedpur, Jharkhand 831001',
            industry: 'Manufacturing',
            companySize: '500+',
            annualRevenue: 420000000,
            website: 'https://www.tatasteel.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2023-08-30').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'IIT Bombay Education Services',
            email: 'admin@iitb.ac.in',
            phone: '+91-22-2572-2545',
            address: 'Indian Institute of Technology Bombay, Powai, Mumbai, Maharashtra 400076',
            industry: 'Education',
            companySize: '201-500',
            annualRevenue: 85000000,
            website: 'https://www.iitb.ac.in',
            assignedAccountManager: 2,
            status: 'active',
            leadId: 12,
            createdAt: new Date('2023-09-20').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            name: 'Blue Dart Logistics',
            email: 'corporate@bluedart.com',
            phone: '+91-22-6279-3333',
            address: 'Blue Dart Centre, Sahar Airport Road, Andheri East, Mumbai, Maharashtra 400099',
            industry: 'Logistics',
            companySize: '500+',
            annualRevenue: 290000000,
            website: 'https://www.bluedart.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: 15,
            createdAt: new Date('2023-11-12').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            name: 'Wipro IT Services',
            email: 'info@wipro.com',
            phone: '+91-80-2844-0011',
            address: 'Doddakannelli, Sarjapur Road, Bangalore, Karnataka 560035',
            industry: 'IT',
            companySize: '500+',
            annualRevenue: 395000000,
            website: 'https://www.wipro.com',
            assignedAccountManager: 3,
            status: 'active',
            leadId: null,
            createdAt: new Date('2023-10-18').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            name: 'Mahindra Auto Manufacturing',
            email: 'corporate@mahindra.com',
            phone: '+91-22-2490-1441',
            address: 'Mahindra Towers, Dr. G. M. Bhosale Marg, Worli, Mumbai, Maharashtra 400018',
            industry: 'Manufacturing',
            companySize: '500+',
            annualRevenue: 310000000,
            website: 'https://www.mahindra.com',
            assignedAccountManager: null,
            status: 'inactive',
            leadId: 3,
            createdAt: new Date('2023-07-08').toISOString(),
            updatedAt: new Date('2023-12-10').toISOString(),
        },
        {
            name: 'Reliance Retail Solutions',
            email: 'business@relianceretail.com',
            phone: '+91-22-3555-5000',
            address: '3rd Floor, Maker Maxity, Bandra Kurla Complex, Bandra East, Mumbai, Maharashtra 400051',
            industry: 'Retail',
            companySize: '500+',
            annualRevenue: 475000000,
            website: 'https://www.relianceretail.com',
            assignedAccountManager: 2,
            status: 'on_hold',
            leadId: 18,
            createdAt: new Date('2023-09-05').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
    ];

    await db.insert(clients).values(sampleClients);
    
    console.log('✅ Clients seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});