import { db } from '@/db';
import { clients } from '@/db/schema';

async function main() {
    const sampleClients = [
        {
            name: 'Infosys Technologies Ltd',
            email: 'contact@infosys.com',
            phone: '+91-80-2852-0261',
            address: 'Electronics City, Hosur Road, Bangalore, Karnataka 560100',
            industry: 'IT',
            companySize: '1000+',
            annualRevenue: 450000000,
            website: 'https://www.infosys.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Apollo Hospitals Enterprise',
            email: 'info@apollohospitals.com',
            phone: '+91-44-2829-3333',
            address: '21, Greams Lane, Off Greams Road, Chennai, Tamil Nadu 600006',
            industry: 'Healthcare',
            companySize: '500-999',
            annualRevenue: 125000000,
            website: 'https://www.apollohospitals.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'HDFC Bank Ltd',
            email: 'customercare@hdfcbank.com',
            phone: '+91-22-6171-6001',
            address: 'HDFC Bank House, Senapati Bapat Marg, Lower Parel, Mumbai, Maharashtra 400013',
            industry: 'Finance',
            companySize: '1000+',
            annualRevenue: 500000000,
            website: 'https://www.hdfcbank.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'BigBasket Retail Pvt Ltd',
            email: 'support@bigbasket.com',
            phone: '+91-80-6163-6163',
            address: 'Embassy Tech Village, Outer Ring Road, Devarabeesanahalli, Bangalore, Karnataka 560103',
            industry: 'Retail',
            companySize: '100-499',
            annualRevenue: 85000000,
            website: 'https://www.bigbasket.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Tata Steel Limited',
            email: 'info@tatasteel.com',
            phone: '+91-657-665-0209',
            address: 'Bistupur, Jamshedpur, Jharkhand 831001',
            industry: 'Manufacturing',
            companySize: '1000+',
            annualRevenue: 380000000,
            website: 'https://www.tatasteel.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Indian Institute of Technology Bombay',
            email: 'office@iitb.ac.in',
            phone: '+91-22-2572-2545',
            address: 'Powai, Mumbai, Maharashtra 400076',
            industry: 'Education',
            companySize: '500-999',
            annualRevenue: 45000000,
            website: 'https://www.iitb.ac.in',
            assignedAccountManager: null,
            status: 'inactive',
            leadId: null,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Blue Dart Express Limited',
            email: 'customercare@bluedart.com',
            phone: '+91-22-6666-7777',
            address: 'Blue Dart Centre, Sahar Airport Road, Andheri East, Mumbai, Maharashtra 400099',
            industry: 'Logistics',
            companySize: '100-499',
            annualRevenue: 65000000,
            website: 'https://www.bluedart.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Wipro IT Services',
            email: 'contact@wipro.com',
            phone: '+91-80-2844-0011',
            address: 'Doddakannelli, Sarjapur Road, Bangalore, Karnataka 560035',
            industry: 'IT',
            companySize: '1000+',
            annualRevenue: 420000000,
            website: 'https://www.wipro.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Mahindra Automotive Ltd',
            email: 'info@mahindra.com',
            phone: '+91-22-2490-1441',
            address: 'Gateway Building, Apollo Bunder, Mumbai, Maharashtra 400001',
            industry: 'Manufacturing',
            companySize: '1000+',
            annualRevenue: 325000000,
            website: 'https://www.mahindra.com',
            assignedAccountManager: null,
            status: 'on_hold',
            leadId: null,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            name: 'Reliance Retail Ventures',
            email: 'customercare@relianceretail.com',
            phone: '+91-22-3555-5000',
            address: '3rd Floor, Maker Chambers IV, 222, Nariman Point, Mumbai, Maharashtra 400021',
            industry: 'Retail',
            companySize: '1000+',
            annualRevenue: 480000000,
            website: 'https://www.relianceretail.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
    ];

    await db.insert(clients).values(sampleClients);
    
    console.log('✅ Clients seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});