import { db } from '@/db';
import { clients } from '@/db/schema';

async function main() {
    const sampleClients = [
        {
            name: 'Infosys Technologies Ltd',
            email: 'contact@infosys.com',
            phone: '+91 80 2852 0261',
            address: 'Electronics City, Hosur Road, Bengaluru, Karnataka 560100',
            industry: 'IT',
            companySize: '500+',
            annualRevenue: 450000000,
            website: 'https://www.infosys.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: 1,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Tech Mahindra Limited',
            email: 'business@techmahindra.com',
            phone: '+91 20 6601 8000',
            address: 'Sharda Centre, Plot No. 156-158, Phase 1, Hinjewadi, Pune, Maharashtra 411057',
            industry: 'IT',
            companySize: '500+',
            annualRevenue: 380000000,
            website: 'https://www.techmahindra.com',
            assignedAccountManager: 2,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            name: 'Apollo Hospitals Enterprise Ltd',
            email: 'info@apollohospitals.com',
            phone: '+91 44 2829 3333',
            address: '21, Greams Lane, Off Greams Road, Chennai, Tamil Nadu 600006',
            industry: 'Healthcare',
            companySize: '201-500',
            annualRevenue: 320000000,
            website: 'https://www.apollohospitals.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: 2,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Fortis Healthcare Limited',
            email: 'corporate@fortishealthcare.com',
            phone: '+91 11 4277 6222',
            address: 'Tower A, Unitech Business Zone, Block F, Sector 50, Gurugram, Haryana 122001',
            industry: 'Healthcare',
            companySize: '201-500',
            annualRevenue: 280000000,
            website: 'https://www.fortishealthcare.com',
            assignedAccountManager: 2,
            status: 'inactive',
            leadId: null,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'HDFC Bank Ltd',
            email: 'corporate@hdfcbank.com',
            phone: '+91 22 6652 1000',
            address: 'HDFC Bank House, Senapati Bapat Marg, Lower Parel, Mumbai, Maharashtra 400013',
            industry: 'Finance',
            companySize: '500+',
            annualRevenue: 500000000,
            website: 'https://www.hdfcbank.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'ICICI Bank Limited',
            email: 'corporate@icicibank.com',
            phone: '+91 22 2653 1414',
            address: 'ICICI Bank Towers, Bandra Kurla Complex, Mumbai, Maharashtra 400051',
            industry: 'Finance',
            companySize: '500+',
            annualRevenue: 480000000,
            website: 'https://www.icicibank.com',
            assignedAccountManager: null,
            status: 'active',
            leadId: 3,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'BigBasket Retail Pvt Ltd',
            email: 'business@bigbasket.com',
            phone: '+91 80 6121 2121',
            address: 'Embassy Tech Village, Devarabeesanahalli, Outer Ring Road, Bengaluru, Karnataka 560103',
            industry: 'Retail',
            companySize: '201-500',
            annualRevenue: 180000000,
            website: 'https://www.bigbasket.com',
            assignedAccountManager: 2,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            name: 'Flipkart Internet Private Limited',
            email: 'corporate@flipkart.com',
            phone: '+91 80 4719 8000',
            address: 'Vaishnavi Summit, Outer Ring Road, Bengaluru, Karnataka 560103',
            industry: 'Retail',
            companySize: '201-500',
            annualRevenue: 350000000,
            website: 'https://www.flipkart.com',
            assignedAccountManager: 1,
            status: 'on_hold',
            leadId: null,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'Tata Steel Limited',
            email: 'corporate@tatasteel.com',
            phone: '+91 657 665 1201',
            address: 'Jamshedpur Works, Jamshedpur, Jharkhand 831001',
            industry: 'Manufacturing',
            companySize: '500+',
            annualRevenue: 420000000,
            website: 'https://www.tatasteel.com',
            assignedAccountManager: 2,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            name: 'Larsen & Toubro Limited',
            email: 'ltinfo@larsentoubro.com',
            phone: '+91 22 6752 5656',
            address: 'L&T House, Ballard Estate, Mumbai, Maharashtra 400001',
            industry: 'Manufacturing',
            companySize: '500+',
            annualRevenue: 460000000,
            website: 'https://www.larsentoubro.com',
            assignedAccountManager: 1,
            status: 'active',
            leadId: null,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
    ];

    await db.insert(clients).values(sampleClients);
    
    console.log('✅ Clients seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});