import { db } from '@/db';
import { communications } from '@/db/schema';

async function main() {
    const sampleCommunications = [
        // Client Communications (10 records)
        {
            clientId: 1,
            leadId: null,
            type: 'email',
            subject: 'Q1 Project Status Update',
            notes: 'Sent comprehensive project status report covering milestone achievements and upcoming deliverables. Client expressed satisfaction with progress on the CRM implementation. Discussed minor scope adjustments for custom reporting dashboard. Action items include scheduling technical review meeting next week and preparing updated timeline document.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-15T10:30:00Z').toISOString(),
            createdAt: new Date('2024-02-15T10:35:00Z').toISOString(),
        },
        {
            clientId: 2,
            leadId: null,
            type: 'meeting',
            subject: 'Contract Renewal Discussion',
            notes: 'Held 45-minute meeting to discuss contract renewal for upcoming year. Client raised concerns about pricing structure and requested volume discount. Reviewed service delivery metrics showing 98% uptime and positive outcomes. Agreed to prepare revised proposal with tiered pricing options. Client indicated strong interest in continuing partnership with improved terms.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-10T14:00:00Z').toISOString(),
            createdAt: new Date('2024-02-10T15:00:00Z').toISOString(),
        },
        {
            clientId: 3,
            leadId: null,
            type: 'phone',
            subject: 'Urgent Support Request Follow-up',
            notes: 'Called to follow up on critical support ticket regarding system downtime. Confirmed that issue has been resolved and service restored. Client appreciated quick response time but requested more proactive monitoring. Discussed implementing enhanced alerting system and scheduled monthly health check calls. Client satisfied with resolution and communication.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-20T09:15:00Z').toISOString(),
            createdAt: new Date('2024-02-20T09:30:00Z').toISOString(),
        },
        {
            clientId: 4,
            leadId: null,
            type: 'chat',
            subject: 'Feature Request Clarification',
            notes: 'Quick chat session regarding new feature request for API integration. Client needs to connect with third-party analytics platform. Gathered technical requirements including API endpoints, authentication methods, and data sync frequency. Estimated 2-3 week development timeline. Will prepare detailed technical specification document by end of week.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-02-18T11:45:00Z').toISOString(),
            createdAt: new Date('2024-02-18T11:50:00Z').toISOString(),
        },
        {
            clientId: 5,
            leadId: null,
            type: 'email',
            subject: 'Quarterly Business Review Invitation',
            notes: 'Sent invitation for upcoming Quarterly Business Review meeting. Outlined agenda including performance metrics review, strategic roadmap discussion, and success story documentation. Requested client to provide feedback on service delivery and identify areas for improvement. Proposed three potential dates for March. Client responded positively and confirmed availability for March 15th.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-05T13:20:00Z').toISOString(),
            createdAt: new Date('2024-02-05T13:25:00Z').toISOString(),
        },
        {
            clientId: 6,
            leadId: null,
            type: 'meeting',
            subject: 'Upsell Opportunity - Premium Support Package',
            notes: 'Presented premium support package including 24/7 coverage, dedicated account manager, and priority response times. Client showed strong interest after recent support experience. Discussed pricing options and service level improvements. Client requested comparison document showing current vs premium service levels. Will send detailed proposal with ROI analysis by end of week.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-12T15:30:00Z').toISOString(),
            createdAt: new Date('2024-02-12T16:15:00Z').toISOString(),
        },
        {
            clientId: 7,
            leadId: null,
            type: 'phone',
            subject: 'Training Session Coordination',
            notes: 'Coordinated upcoming training session for client team on new system features. Discussed training objectives, participant list, and preferred format. Client requested hands-on workshop style with real-world scenarios. Scheduled two half-day sessions for next month to accommodate all team members. Will prepare customized training materials based on their specific use cases.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-02-08T10:00:00Z').toISOString(),
            createdAt: new Date('2024-02-08T10:15:00Z').toISOString(),
        },
        {
            clientId: 8,
            leadId: null,
            type: 'chat',
            subject: 'Invoice Inquiry',
            notes: 'Client inquired about recent invoice discrepancy regarding additional user licenses. Reviewed account history and identified billing error from our side. Apologized for confusion and confirmed corrected invoice will be issued within 24 hours. Client appreciated quick response and transparent communication. Applied courtesy discount for inconvenience caused.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-22T14:30:00Z').toISOString(),
            createdAt: new Date('2024-02-22T14:35:00Z').toISOString(),
        },
        {
            clientId: 9,
            leadId: null,
            type: 'email',
            subject: 'Success Story Documentation Request',
            notes: 'Reached out to document client success story for marketing purposes. Client achieved 40% efficiency improvement using our platform and willing to participate in case study. Scheduled interview session with their operations manager. Discussed approval process and timeline for publication. Client enthusiastic about sharing their positive experience and outcomes.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-14T16:00:00Z').toISOString(),
            createdAt: new Date('2024-02-14T16:10:00Z').toISOString(),
        },
        {
            clientId: 10,
            leadId: null,
            type: 'meeting',
            subject: 'Strategic Planning Session',
            notes: 'Conducted strategic planning session to align our services with client digital transformation initiatives. Discussed upcoming projects, technology roadmap, and potential collaboration opportunities. Client shared ambitious growth plans and need for scalable solutions. Identified three specific areas where we can add value. Action items include preparing detailed proposal for expanded partnership and scheduling follow-up in two weeks.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-02-25T11:00:00Z').toISOString(),
            createdAt: new Date('2024-02-25T12:30:00Z').toISOString(),
        },
        
        // Lead Communications (10 records)
        {
            clientId: null,
            leadId: 5,
            type: 'email',
            subject: 'Initial Discovery Call Follow-up',
            notes: 'Sent follow-up email after discovery call summarizing pain points and requirements. Lead looking for automation solution to streamline operations. Attached relevant case studies from similar industry clients. Proposed three time slots for product demo next week. Emphasized ROI potential based on their current manual processes. Lead responded positively and confirmed interest.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-16T09:30:00Z').toISOString(),
            createdAt: new Date('2024-02-16T09:40:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 8,
            type: 'phone',
            subject: 'Product Demo Scheduling',
            notes: 'Called to schedule personalized product demonstration. Lead interested in seeing specific features related to reporting and analytics. Discussed their current challenges with data visibility and manual reporting. Confirmed demo session for next Tuesday with key stakeholders including CFO and IT manager. Will prepare customized demo focusing on their specific use cases.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-11T15:20:00Z').toISOString(),
            createdAt: new Date('2024-02-11T15:30:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 10,
            type: 'meeting',
            subject: 'Live Product Demonstration',
            notes: 'Conducted comprehensive 60-minute product demo showcasing key features and capabilities. Lead impressed with user interface and integration possibilities. Addressed questions about data security, compliance, and scalability. Demonstrated mobile app functionality which was critical requirement. Lead requested detailed pricing proposal and implementation timeline. Strong buying signals observed. Next step is preparing formal proposal.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-02-19T14:00:00Z').toISOString(),
            createdAt: new Date('2024-02-19T15:30:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 12,
            type: 'email',
            subject: 'Proposal Submission and Walkthrough',
            notes: 'Submitted detailed proposal including pricing options, implementation plan, and support packages. Proposal structured with three tiers to provide flexibility. Highlighted key differentiators and competitive advantages. Included references from similar industry clients and success metrics. Requested meeting to walk through proposal and address any questions. Lead acknowledged receipt and scheduled review meeting for next week.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-13T10:15:00Z').toISOString(),
            createdAt: new Date('2024-02-13T10:25:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 14,
            type: 'phone',
            subject: 'Objection Handling - Budget Concerns',
            notes: 'Lead expressed concerns about pricing being above allocated budget. Discussed flexible payment options including monthly subscription vs annual commitment. Explained value proposition and ROI timeline showing break-even within 8 months. Offered to adjust scope to fit budget while maintaining core functionality. Lead appreciated flexibility and agreed to discuss internally with finance team.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-21T11:45:00Z').toISOString(),
            createdAt: new Date('2024-02-21T12:00:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 15,
            type: 'chat',
            subject: 'Technical Questions Follow-up',
            notes: 'Lead had technical questions about API capabilities and data migration process. Provided detailed responses about REST API documentation, webhook support, and available integrations. Discussed data migration approach including validation steps and rollback procedures. Offered to connect them with technical team for deeper dive. Lead satisfied with technical capabilities and moving forward with evaluation.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-02-17T16:20:00Z').toISOString(),
            createdAt: new Date('2024-02-17T16:30:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 16,
            type: 'meeting',
            subject: 'Stakeholder Presentation',
            notes: 'Presented to extended stakeholder group including CEO, CTO, and department heads. Tailored presentation to address each stakeholder concern - CEO focused on ROI, CTO on technical architecture, operations on usability. Q&A session lasted 30 minutes with detailed technical and business questions. Strong positive reception from all stakeholders. CEO requested final proposal with implementation roadmap.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-23T13:00:00Z').toISOString(),
            createdAt: new Date('2024-02-23T15:00:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 18,
            type: 'email',
            subject: 'Competitive Analysis Response',
            notes: 'Lead evaluating multiple vendors and requested detailed comparison. Prepared comprehensive competitive analysis highlighting our strengths in customer support, implementation speed, and integration ecosystem. Addressed specific competitor weaknesses without negative positioning. Included customer testimonials and third-party reviews. Emphasized unique features and superior onboarding process. Lead appreciated transparency and thoroughness.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-02-09T14:45:00Z').toISOString(),
            createdAt: new Date('2024-02-09T15:00:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 5,
            type: 'phone',
            subject: 'Contract Negotiation Discussion',
            notes: 'Lead ready to move forward but requesting modifications to standard contract terms. Discussed payment terms, service level agreements, and termination clauses. Lead concerned about data ownership and exit strategy. Explained our transparent data portability policy and customer-friendly terms. Agreed to have legal teams review modified contract. Strong indication of imminent deal closure.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-02-26T10:30:00Z').toISOString(),
            createdAt: new Date('2024-02-26T10:45:00Z').toISOString(),
        },
        {
            clientId: null,
            leadId: 8,
            type: 'email',
            subject: 'Free Trial Setup and Onboarding',
            notes: 'Lead requested trial period before final commitment. Set up 30-day trial account with full feature access. Prepared personalized onboarding plan including training sessions and check-in calls. Assigned dedicated trial support contact for immediate assistance. Shared success criteria and evaluation framework. Scheduled kick-off call to ensure smooth trial experience. Lead excited to test platform with real data.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-02-24T12:00:00Z').toISOString(),
            createdAt: new Date('2024-02-24T12:15:00Z').toISOString(),
        },
    ];

    await db.insert(communications).values(sampleCommunications);
    
    console.log('✅ Communications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});