import { db } from '@/db';
import { communications } from '@/db/schema';

async function main() {
    const sampleCommunications = [
        {
            type: 'email',
            clientId: 1,
            leadId: null,
            subject: 'Q1 Project Kickoff Meeting',
            notes: 'Discussed project scope and timeline for the new CRM implementation. Client requested additional features including custom reporting dashboard and mobile app integration. Agreed to schedule follow-up technical discussion next week. Action items: Send detailed project proposal and resource allocation plan.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-10-15T10:30:00').toISOString(),
            createdAt: new Date('2024-10-15T10:35:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: null,
            leadId: 5,
            subject: 'Initial Discovery Call',
            notes: 'Had productive conversation about their current pain points with manual attendance tracking. Lead expressed strong interest in our NFC-based solution. Company has 150 employees across 3 locations. Budget range: $15,000-$20,000. Next step: Schedule demo for their management team.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-10-18T14:00:00').toISOString(),
            createdAt: new Date('2024-10-18T14:15:00').toISOString(),
        },
        {
            type: 'meeting',
            clientId: 3,
            leadId: null,
            subject: 'Contract Renewal Discussion',
            notes: 'In-person meeting at client office. Reviewed performance metrics from past year - 99.2% uptime achieved. Discussed pricing structure for contract renewal. Client satisfied with service quality but requested volume discount due to expanding to 2 new offices. Agreed to 12% discount with 2-year commitment. Follow-up: Send updated contract terms by Friday.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-10-22T11:00:00').toISOString(),
            createdAt: new Date('2024-10-22T13:20:00').toISOString(),
        },
        {
            type: 'email',
            clientId: null,
            leadId: 12,
            subject: 'Proposal Follow-up',
            notes: 'Sent detailed proposal for HR management solution. Highlighted key features: automated payroll processing, expense management, and compliance reporting. Included case studies from similar-sized companies. Lead acknowledged receipt and mentioned they are evaluating 3 vendors. Expected decision timeline: 2 weeks. Scheduled presentation for next Tuesday.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-10-25T09:15:00').toISOString(),
            createdAt: new Date('2024-10-25T09:15:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: 5,
            leadId: null,
            subject: 'Technical Support - Invoice Integration',
            notes: 'Client reported issues with invoice PDF generation. Investigated and found issue with custom template rendering. Provided temporary workaround using standard template. Escalated to development team for permanent fix. Client satisfied with quick response time. Estimated fix deployment: 48 hours. Will follow up post-deployment.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-10-28T15:45:00').toISOString(),
            createdAt: new Date('2024-10-28T16:00:00').toISOString(),
        },
        {
            type: 'email',
            clientId: 7,
            leadId: null,
            subject: 'Monthly Performance Review',
            notes: 'Shared comprehensive monthly report covering attendance tracking accuracy, payroll processing metrics, and system uptime statistics. Client feedback: Very pleased with automated reporting feature. Requested additional custom reports for department-wise expense analysis. Action: Configure custom report templates and schedule training session for their finance team.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-11-01T10:00:00').toISOString(),
            createdAt: new Date('2024-11-01T10:05:00').toISOString(),
        },
        {
            type: 'meeting',
            clientId: null,
            leadId: 8,
            subject: 'Product Demo and Requirements Gathering',
            notes: 'Conducted 90-minute product demonstration covering all modules. Lead was impressed with the invoice management and client portal features. Discussed their specific requirements: multi-currency support, integration with existing accounting software (QuickBooks), and role-based access control. Team size: 45 employees. Budget approved: $12,000. Next steps: Prepare customized proposal and implementation timeline.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-11-05T13:30:00').toISOString(),
            createdAt: new Date('2024-11-05T15:00:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: null,
            leadId: 15,
            subject: 'Pricing Clarification Call',
            notes: 'Lead had questions about pricing tiers and feature availability. Explained difference between Standard and Enterprise plans. They need expense management and advanced reporting but currently only have 20 employees. Suggested starting with Standard plan with option to upgrade. Addressed concerns about data migration from their current system. Sending comparison chart and migration guide via email.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-11-08T11:20:00').toISOString(),
            createdAt: new Date('2024-11-08T11:35:00').toISOString(),
        },
        {
            type: 'email',
            clientId: 2,
            leadId: null,
            subject: 'Quarterly Business Review',
            notes: 'Comprehensive review of Q3 performance metrics. Highlighted achievements: 40% reduction in payroll processing time, 95% employee adoption rate for mobile attendance app. Discussed expansion opportunities: Adding contract management module and implementing SLA tracking. Client requested ROI analysis and feature roadmap for next 6 months. Scheduling executive presentation for November 20th.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-11-12T14:30:00').toISOString(),
            createdAt: new Date('2024-11-12T14:30:00').toISOString(),
        },
        {
            type: 'chat',
            clientId: 4,
            leadId: null,
            subject: 'Quick Question - Employee Onboarding',
            notes: 'Client asked via live chat about bulk employee onboarding process. Explained CSV import feature and template format. Shared step-by-step guide and video tutorial link. Client successfully imported 15 new employees. Also inquired about NFC card distribution timeline - confirmed cards will be shipped within 3 business days.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-11-15T16:45:00').toISOString(),
            createdAt: new Date('2024-11-15T16:50:00').toISOString(),
        },
        {
            type: 'meeting',
            clientId: 6,
            leadId: null,
            subject: 'Feature Request Discussion',
            notes: 'Client requested new features for their growing organization: Shift scheduling module, overtime calculations with configurable rules, and integration with their biometric devices. Detailed discussion about technical feasibility and implementation timeline. Estimated development time: 6-8 weeks. Client willing to participate in beta testing. Action: Prepare detailed scope document and revised pricing proposal.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-11-18T10:30:00').toISOString(),
            createdAt: new Date('2024-11-18T11:45:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: null,
            leadId: 3,
            subject: 'Budget Approval Follow-up',
            notes: 'Follow-up call regarding proposal sent 2 weeks ago. Lead confirmed budget has been approved by management. Ready to proceed with implementation. Discussed onboarding timeline: 2-week implementation, 1-week training, 1-week transition period. Addressing last concerns about data security and compliance with local labor laws. Sending MSA and implementation agreement for review.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-11-20T09:30:00').toISOString(),
            createdAt: new Date('2024-11-20T09:45:00').toISOString(),
        },
        {
            type: 'email',
            clientId: 8,
            leadId: null,
            subject: 'System Upgrade Notification',
            notes: 'Notified client about upcoming system upgrade including new features: Enhanced mobile app with offline mode, improved invoice templates, and automated expense approval workflows. Scheduled upgrade for this Saturday at 2 AM with estimated 4-hour downtime. Client acknowledged and requested post-upgrade training session for their team. Training scheduled for next Monday.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-11-22T11:00:00').toISOString(),
            createdAt: new Date('2024-11-22T11:00:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: null,
            leadId: 10,
            subject: 'Competitive Comparison Discussion',
            notes: 'Lead currently using competitor solution, experiencing issues with customer support and limited customization options. Discussed our advantages: 24/7 support, flexible customization, and lower total cost of ownership. Lead particularly interested in our attendance geo-fencing feature and automated compliance reporting. Requested references from similar clients in their industry. Sending case studies and arranging reference call.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-11-25T15:15:00').toISOString(),
            createdAt: new Date('2024-11-25T15:30:00').toISOString(),
        },
        {
            type: 'meeting',
            clientId: 9,
            leadId: null,
            subject: 'Annual Contract Review and Expansion',
            notes: 'Positive review meeting covering year 1 performance. Client extremely satisfied with system reliability and support quality. Discussed expansion: Adding CRM module, implementing project management features, and integrating with their existing ERP system. Client also referred us to their parent company (300+ employees). Agreed on 15% discount for expanded services. Contract value increasing from $18,000 to $45,000 annually.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-11-28T14:00:00').toISOString(),
            createdAt: new Date('2024-11-28T16:00:00').toISOString(),
        },
        {
            type: 'email',
            clientId: null,
            leadId: 7,
            subject: 'Custom Solution Proposal',
            notes: 'Lead requires highly customized solution for their unique business model (consulting firm with project-based billing). Prepared detailed proposal covering: Time tracking integration with project codes, automated client billing based on hourly rates, expense allocation by project, and custom reporting for project profitability. Proposal value: $25,000 implementation + $800/month subscription. Awaiting management review.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-12-01T10:30:00').toISOString(),
            createdAt: new Date('2024-12-01T10:30:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: 10,
            leadId: null,
            subject: 'Integration Support Call',
            notes: 'Assisted client with API integration for their custom reporting dashboard. Walked through authentication process, endpoint documentation, and rate limits. Client developer had questions about webhook configuration for real-time attendance updates. Provided code samples and tested webhook delivery. Integration successfully completed during call. Client very satisfied with API documentation quality.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-12-04T13:00:00').toISOString(),
            createdAt: new Date('2024-12-04T13:25:00').toISOString(),
        },
        {
            type: 'chat',
            clientId: null,
            leadId: 18,
            subject: 'Initial Inquiry - Product Features',
            notes: 'Lead reached out via website chat asking about attendance tracking capabilities. Explained NFC card system, mobile app check-in, GPS tracking, and automated notifications. Lead interested in trial period. Company details: Retail chain with 8 locations, 120 employees total. Main concern: Managing attendance across multiple locations. Scheduled demo call for next week and sent product brochure.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-12-06T16:20:00').toISOString(),
            createdAt: new Date('2024-12-06T16:25:00').toISOString(),
        },
        {
            type: 'email',
            clientId: 1,
            leadId: null,
            subject: 'Compliance Audit Support',
            notes: 'Client preparing for annual compliance audit, requested documentation for attendance records, payroll calculations, and tax filings. Generated comprehensive reports covering entire fiscal year. Provided system access to their auditor with read-only permissions. Explained data retention policies and backup procedures. Client appreciated quick turnaround. Audit completed successfully with no issues.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-12-09T09:00:00').toISOString(),
            createdAt: new Date('2024-12-09T09:00:00').toISOString(),
        },
        {
            type: 'meeting',
            clientId: null,
            leadId: 14,
            subject: 'Executive Presentation - Enterprise Solution',
            notes: 'Presented to C-level executives of potential enterprise client (500+ employees, multi-national operations). Covered: Scalability, security compliance (SOC 2, GDPR), multi-currency and multi-language support, and dedicated account management. Strong interest in our SLA offerings and disaster recovery capabilities. Budget range: $75,000-$100,000 annually. Decision committee meeting scheduled for December 20th. High probability deal.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-12-11T11:00:00').toISOString(),
            createdAt: new Date('2024-12-11T13:30:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: 3,
            leadId: null,
            subject: 'Year-End Processing Support',
            notes: 'Guided client through year-end payroll processing and tax form generation. Explained updated tax slabs and compliance requirements for new fiscal year. Assisted with bulk Form 16 generation for all employees. Client needed help with previous year corrections - processed amendments for 5 employees. Discussed upcoming statutory changes and system updates to support new compliance requirements.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-12-13T14:30:00').toISOString(),
            createdAt: new Date('2024-12-13T14:45:00').toISOString(),
        },
        {
            type: 'email',
            clientId: null,
            leadId: 16,
            subject: 'Trial Period Results and Conversion',
            notes: 'Lead completed 30-day trial period with excellent results. Their feedback: Easy to use, significant time savings in payroll processing (reduced from 3 days to 4 hours), and employees loved the mobile app. Ready to convert to paid subscription. Company size: 35 employees. Selected Professional plan at $450/month. Requesting one-time data migration assistance from trial to production. Conversion scheduled for January 1st.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-12-15T10:15:00').toISOString(),
            createdAt: new Date('2024-12-15T10:15:00').toISOString(),
        },
        {
            type: 'phone',
            clientId: 7,
            leadId: null,
            subject: 'Success Story Interview',
            notes: 'Conducted interview for case study publication. Client shared their success story: 60% reduction in administrative overhead, improved employee satisfaction scores, and better compliance tracking. Discussed specific metrics and ROI achieved. Client agreed to participate in joint webinar in Q1 2025 and willing to serve as reference for enterprise leads. Great relationship building opportunity.',
            userId: 'user_01h4kxt2e8z9y3b1n7m6q5w8r4',
            communicationDate: new Date('2024-12-17T15:00:00').toISOString(),
            createdAt: new Date('2024-12-17T15:20:00').toISOString(),
        },
        {
            type: 'meeting',
            clientId: 5,
            leadId: null,
            subject: 'Strategic Planning Session',
            notes: 'Quarterly strategic planning meeting with client stakeholders. Reviewed Q4 achievements and planned initiatives for 2025. Client goals: Implement advanced analytics dashboard, automate more approval workflows, and expand system usage to their subsidiary companies. Discussed our product roadmap alignment with their needs. Agreed on pilot program for subsidiary rollout starting February. Strong partnership continuing to grow.',
            userId: 'user_9k2mxt8p5r1y7b3n4q6w2h5c1',
            communicationDate: new Date('2024-12-19T13:00:00').toISOString(),
            createdAt: new Date('2024-12-19T14:30:00').toISOString(),
        },
        {
            type: 'email',
            clientId: null,
            leadId: 11,
            subject: 'Holiday Season Special Offer Follow-up',
            notes: 'Follow-up on special year-end pricing offer sent last week. Lead expressed interest but needs to finalize budget approval before year-end. Offer includes: 20% discount on annual subscription, free implementation, and 3 months of premium support. Lead confirmed decision will be made by December 27th. They have requested extension of offer validity until January 5th - approved by sales manager.',
            userId: 'user_7h5pxt9r2k4y1b8n3q2w6m5c7',
            communicationDate: new Date('2024-12-20T11:30:00').toISOString(),
            createdAt: new Date('2024-12-20T11:30:00').toISOString(),
        },
    ];

    await db.insert(communications).values(sampleCommunications);
    
    console.log('✅ Communications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});