import { db } from '@/db';
import { contracts } from '@/db/schema';

async function main() {
    const sampleContracts = [
        {
            clientId: 1,
            contractNumber: 'CONT-2024-001',
            title: 'Annual Software Maintenance Agreement',
            description: 'Comprehensive software maintenance and support services including bug fixes, security updates, and technical support for enterprise applications.',
            value: 2500000,
            startDate: new Date('2024-01-15').toISOString(),
            endDate: new Date('2026-01-14').toISOString(),
            status: 'active',
            documentUrl: 'https://contracts.example.com/CONT-2024-001.pdf',
            signedBy: 'Rajesh Kumar',
            signedAt: new Date('2024-01-10').toISOString(),
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            clientId: 3,
            contractNumber: 'CONT-2024-002',
            title: 'Cloud Infrastructure Services',
            description: 'AWS cloud infrastructure management, monitoring, optimization, and 24/7 technical support services for production workloads.',
            value: 8500000,
            startDate: new Date('2023-11-01').toISOString(),
            endDate: new Date('2026-10-31').toISOString(),
            status: 'active',
            documentUrl: 'https://contracts.example.com/CONT-2024-002.pdf',
            signedBy: 'Priya Sharma',
            signedAt: new Date('2023-10-28').toISOString(),
            createdAt: new Date('2023-10-15').toISOString(),
            updatedAt: new Date('2023-10-28').toISOString(),
        },
        {
            clientId: 5,
            contractNumber: 'CONT-2024-003',
            title: 'IT Consulting and Advisory Services',
            description: 'Strategic IT consulting services covering digital transformation, technology roadmap planning, and system architecture design.',
            value: 5000000,
            startDate: new Date('2024-02-01').toISOString(),
            endDate: new Date('2025-01-31').toISOString(),
            status: 'active',
            documentUrl: 'https://contracts.example.com/CONT-2024-003.pdf',
            signedBy: 'Amit Patel',
            signedAt: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            clientId: 7,
            contractNumber: 'CONT-2024-004',
            title: 'Mobile Application Development',
            description: 'Design and development of cross-platform mobile applications for iOS and Android, including UI/UX design, development, testing, and deployment.',
            value: 3500000,
            startDate: new Date('2023-09-15').toISOString(),
            endDate: new Date('2024-09-14').toISOString(),
            status: 'active',
            documentUrl: 'https://contracts.example.com/CONT-2024-004.pdf',
            signedBy: 'Neha Gupta',
            signedAt: new Date('2023-09-10').toISOString(),
            createdAt: new Date('2023-09-01').toISOString(),
            updatedAt: new Date('2023-09-10').toISOString(),
        },
        {
            clientId: 2,
            contractNumber: 'CONT-2024-005',
            title: 'Cybersecurity Assessment and Implementation',
            description: 'Comprehensive security audit, vulnerability assessment, penetration testing, and implementation of security best practices and compliance measures.',
            value: 6500000,
            startDate: new Date('2024-05-01').toISOString(),
            endDate: new Date('2025-04-30').toISOString(),
            status: 'draft',
            documentUrl: 'https://contracts.example.com/CONT-2024-005.pdf',
            signedBy: null,
            signedAt: null,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            clientId: 8,
            contractNumber: 'CONT-2024-006',
            title: 'Data Analytics and Business Intelligence Platform',
            description: 'Implementation of enterprise-grade data analytics platform including ETL processes, data warehousing, reporting dashboards, and predictive analytics.',
            value: 10000000,
            startDate: new Date('2024-06-15').toISOString(),
            endDate: new Date('2026-06-14').toISOString(),
            status: 'draft',
            documentUrl: 'https://contracts.example.com/CONT-2024-006.pdf',
            signedBy: null,
            signedAt: null,
            createdAt: new Date('2024-03-25').toISOString(),
            updatedAt: new Date('2024-03-28').toISOString(),
        },
        {
            clientId: 4,
            contractNumber: 'CONT-2023-007',
            title: 'Legacy System Modernization',
            description: 'Migration of legacy enterprise systems to modern cloud-based architecture with improved scalability, security, and performance.',
            value: 7500000,
            startDate: new Date('2023-04-01').toISOString(),
            endDate: new Date('2024-03-31').toISOString(),
            status: 'expired',
            documentUrl: 'https://contracts.example.com/CONT-2023-007.pdf',
            signedBy: 'Vikram Singh',
            signedAt: new Date('2023-03-25').toISOString(),
            createdAt: new Date('2023-03-15').toISOString(),
            updatedAt: new Date('2024-03-31').toISOString(),
        },
    ];

    await db.insert(contracts).values(sampleContracts);
    
    console.log('✅ Contracts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});