import { db } from '@/db';
import { employees } from '@/db/schema';

async function main() {
    const sampleEmployees = [
        // Salaried Employees - Engineering (6)
        {
            name: 'Rajesh Kumar',
            email: 'rajesh.kumar@company.com',
            nfcCardId: 'NFC-1234-5678',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh Kumar',
            salary: 75000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-05').toISOString(),
            createdAt: new Date('2024-01-03').toISOString(),
        },
        {
            name: 'Priya Sharma',
            email: 'priya.sharma@company.com',
            nfcCardId: 'NFC-2345-6789',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya Sharma',
            salary: 68000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-10').toISOString(),
            createdAt: new Date('2024-01-08').toISOString(),
        },
        {
            name: 'Amit Patel',
            email: 'amit.patel@company.com',
            nfcCardId: 'NFC-3456-7890',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Amit Patel',
            salary: 72000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-15').toISOString(),
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            name: 'Sneha Reddy',
            email: 'sneha.reddy@company.com',
            nfcCardId: 'NFC-4567-8901',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sneha Reddy',
            salary: 65000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-20').toISOString(),
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Vikram Singh',
            email: 'vikram.singh@company.com',
            nfcCardId: 'NFC-5678-9012',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram Singh',
            salary: 80000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-02-01').toISOString(),
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'Ananya Desai',
            email: 'ananya.desai@company.com',
            nfcCardId: null,
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ananya Desai',
            salary: 62000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-03-15').toISOString(),
            createdAt: new Date('2024-03-13').toISOString(),
        },
        // Salaried Employees - Engineering (2 more)
        {
            name: 'Karthik Nair',
            email: 'karthik.nair@company.com',
            nfcCardId: 'NFC-6789-0123',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Karthik Nair',
            salary: 70000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-02-10').toISOString(),
            createdAt: new Date('2024-02-08').toISOString(),
        },
        {
            name: 'Divya Iyer',
            email: 'divya.iyer@company.com',
            nfcCardId: 'NFC-7890-1234',
            department: 'Engineering',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Divya Iyer',
            salary: 67000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-02-15').toISOString(),
            createdAt: new Date('2024-02-13').toISOString(),
        },
        // Salaried Employees - HR (3)
        {
            name: 'Neha Gupta',
            email: 'neha.gupta@company.com',
            nfcCardId: 'NFC-8901-2345',
            department: 'HR',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Neha Gupta',
            salary: 55000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-08').toISOString(),
            createdAt: new Date('2024-01-06').toISOString(),
        },
        {
            name: 'Rahul Verma',
            email: 'rahul.verma@company.com',
            nfcCardId: 'NFC-9012-3456',
            department: 'HR',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rahul Verma',
            salary: 52000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-25').toISOString(),
            createdAt: new Date('2024-01-23').toISOString(),
        },
        {
            name: 'Pooja Mehta',
            email: 'pooja.mehta@company.com',
            nfcCardId: 'NFC-0123-4567',
            department: 'HR',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pooja Mehta',
            salary: 48000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-02-20').toISOString(),
            createdAt: new Date('2024-02-18').toISOString(),
        },
        // Salaried Employees - Finance (3)
        {
            name: 'Suresh Joshi',
            email: 'suresh.joshi@company.com',
            nfcCardId: 'NFC-1357-2468',
            department: 'Finance',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Suresh Joshi',
            salary: 58000,
            hourlyRate: null,
            status: 'active',
            enrollmentDate: new Date('2024-01-12').toISOString(),
            createdAt: new Date('2024-01-10').toISOString(),
        },
        // Hourly Employees - Finance (2)
        {
            name: 'Meera Bose',
            email: 'meera.bose@company.com',
            nfcCardId: 'NFC-2468-1357',
            department: 'Finance',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Meera Bose',
            salary: null,
            hourlyRate: 350,
            status: 'active',
            enrollmentDate: new Date('2024-02-05').toISOString(),
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: 'Arun Kapoor',
            email: 'arun.kapoor@company.com',
            nfcCardId: 'NFC-3579-4680',
            department: 'Finance',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arun Kapoor',
            salary: null,
            hourlyRate: 320,
            status: 'active',
            enrollmentDate: new Date('2024-03-01').toISOString(),
            createdAt: new Date('2024-02-28').toISOString(),
        },
        // Hourly Employees - Marketing (3)
        {
            name: 'Kavita Rao',
            email: 'kavita.rao@company.com',
            nfcCardId: 'NFC-4680-3579',
            department: 'Marketing',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Kavita Rao',
            salary: null,
            hourlyRate: 420,
            status: 'active',
            enrollmentDate: new Date('2024-01-18').toISOString(),
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            name: 'Sanjay Pillai',
            email: 'sanjay.pillai@company.com',
            nfcCardId: 'NFC-5791-6802',
            department: 'Marketing',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sanjay Pillai',
            salary: null,
            hourlyRate: 380,
            status: 'active',
            enrollmentDate: new Date('2024-02-12').toISOString(),
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Ritu Bhatt',
            email: 'ritu.bhatt@company.com',
            nfcCardId: 'NFC-6802-5791',
            department: 'Marketing',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ritu Bhatt',
            salary: null,
            hourlyRate: 450,
            status: 'active',
            enrollmentDate: new Date('2024-03-05').toISOString(),
            createdAt: new Date('2024-03-03').toISOString(),
        },
        // Hourly Employees - Sales (3)
        {
            name: 'Manish Agarwal',
            email: 'manish.agarwal@company.com',
            nfcCardId: 'NFC-7913-8024',
            department: 'Sales',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Manish Agarwal',
            salary: null,
            hourlyRate: 500,
            status: 'active',
            enrollmentDate: new Date('2024-01-22').toISOString(),
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Simran Kaur',
            email: 'simran.kaur@company.com',
            nfcCardId: 'NFC-8024-7913',
            department: 'Sales',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Simran Kaur',
            salary: null,
            hourlyRate: 280,
            status: 'active',
            enrollmentDate: new Date('2024-02-18').toISOString(),
            createdAt: new Date('2024-02-16').toISOString(),
        },
        {
            name: 'Arjun Malhotra',
            email: 'arjun.malhotra@company.com',
            nfcCardId: null,
            department: 'Sales',
            photoUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Arjun Malhotra',
            salary: null,
            hourlyRate: 250,
            status: 'active',
            enrollmentDate: new Date('2024-03-20').toISOString(),
            createdAt: new Date('2024-03-18').toISOString(),
        },
    ];

    await db.insert(employees).values(sampleEmployees);
    
    console.log('✅ Employees seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});