import { db } from '@/db';
import { expenses } from '@/db/schema';

async function main() {
    const sampleExpenses = [
        // Pending expenses (5)
        {
            employeeId: 1,
            category: 'travel',
            description: 'Client meeting - Bangalore to Mumbai flight tickets for Q1 review',
            amount: 12500.00,
            expenseDate: new Date('2024-03-15').toISOString(),
            status: 'pending',
            receiptUrl: 'https://receipts.example.com/flight-001.pdf',
            approverId: null,
            approvalDate: null,
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Urgent client meeting, booked economy class',
            createdAt: new Date('2024-03-15T10:30:00').toISOString(),
            updatedAt: new Date('2024-03-15T10:30:00').toISOString(),
        },
        {
            employeeId: 2,
            category: 'food',
            description: 'Team lunch at office cafeteria - Monthly team building activity',
            amount: 1850.00,
            expenseDate: new Date('2024-03-18').toISOString(),
            status: 'pending',
            receiptUrl: null,
            approverId: null,
            approvalDate: null,
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Team of 8 members',
            createdAt: new Date('2024-03-18T15:45:00').toISOString(),
            updatedAt: new Date('2024-03-18T15:45:00').toISOString(),
        },
        {
            employeeId: 3,
            category: 'transport',
            description: 'Uber rides for office commute during late-night deployment',
            amount: 680.00,
            expenseDate: new Date('2024-03-17').toISOString(),
            status: 'pending',
            receiptUrl: 'https://receipts.example.com/uber-march.pdf',
            approverId: null,
            approvalDate: null,
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Production deployment required late-night work',
            createdAt: new Date('2024-03-17T08:20:00').toISOString(),
            updatedAt: new Date('2024-03-17T08:20:00').toISOString(),
        },
        {
            employeeId: 4,
            category: 'software',
            description: 'Adobe Creative Cloud subscription - Annual plan for design team',
            amount: 8999.00,
            expenseDate: new Date('2024-03-20').toISOString(),
            status: 'pending',
            receiptUrl: 'https://receipts.example.com/adobe-inv-2024.pdf',
            approverId: null,
            approvalDate: null,
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Required for ongoing marketing campaigns',
            createdAt: new Date('2024-03-20T11:15:00').toISOString(),
            updatedAt: new Date('2024-03-20T11:15:00').toISOString(),
        },
        {
            employeeId: 5,
            category: 'training',
            description: 'AWS Solutions Architect certification course enrollment',
            amount: 14500.00,
            expenseDate: new Date('2024-03-19').toISOString(),
            status: 'pending',
            receiptUrl: 'https://receipts.example.com/aws-training.pdf',
            approverId: null,
            approvalDate: null,
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Course starts April 1st, certification exam included',
            createdAt: new Date('2024-03-19T14:00:00').toISOString(),
            updatedAt: new Date('2024-03-19T14:00:00').toISOString(),
        },
        // Approved expenses with paid reimbursement (4)
        {
            employeeId: 1,
            category: 'travel',
            description: 'Hotel accommodation in Delhi for conference - 3 nights',
            amount: 9500.00,
            expenseDate: new Date('2024-02-10').toISOString(),
            status: 'approved',
            receiptUrl: 'https://receipts.example.com/hotel-001.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-02-12').toISOString(),
            reimbursementStatus: 'paid',
            reimbursementDate: new Date('2024-02-28').toISOString(),
            notes: 'Industry conference attendance',
            createdAt: new Date('2024-02-10T09:00:00').toISOString(),
            updatedAt: new Date('2024-02-28T10:30:00').toISOString(),
        },
        {
            employeeId: 2,
            category: 'supplies',
            description: 'Office stationery and supplies - Quarterly stock replenishment',
            amount: 3200.00,
            expenseDate: new Date('2024-02-05').toISOString(),
            status: 'approved',
            receiptUrl: 'https://receipts.example.com/supplies-feb.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-02-07').toISOString(),
            reimbursementStatus: 'paid',
            reimbursementDate: new Date('2024-02-25').toISOString(),
            notes: 'Includes paper, pens, folders, and desk organizers',
            createdAt: new Date('2024-02-05T13:20:00').toISOString(),
            updatedAt: new Date('2024-02-25T11:00:00').toISOString(),
        },
        {
            employeeId: 3,
            category: 'food',
            description: 'Client dinner at The Taj - Business development meeting',
            amount: 5800.00,
            expenseDate: new Date('2024-01-28').toISOString(),
            status: 'approved',
            receiptUrl: 'https://receipts.example.com/taj-dinner.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-01-30').toISOString(),
            reimbursementStatus: 'paid',
            reimbursementDate: new Date('2024-02-15').toISOString(),
            notes: 'Potential client worth 50L annual contract',
            createdAt: new Date('2024-01-28T20:30:00').toISOString(),
            updatedAt: new Date('2024-02-15T09:45:00').toISOString(),
        },
        {
            employeeId: 4,
            category: 'transport',
            description: 'Airport taxi service for international client pickup',
            amount: 950.00,
            expenseDate: new Date('2024-02-15').toISOString(),
            status: 'approved',
            receiptUrl: null,
            approverId: 'user_123',
            approvalDate: new Date('2024-02-16').toISOString(),
            reimbursementStatus: 'paid',
            reimbursementDate: new Date('2024-03-01').toISOString(),
            notes: 'Client visit for project kickoff',
            createdAt: new Date('2024-02-15T07:00:00').toISOString(),
            updatedAt: new Date('2024-03-01T10:15:00').toISOString(),
        },
        // Approved expenses with pending reimbursement (3)
        {
            employeeId: 5,
            category: 'software',
            description: 'GitHub Enterprise subscription - Team license for 10 developers',
            amount: 7200.00,
            expenseDate: new Date('2024-03-05').toISOString(),
            status: 'approved',
            receiptUrl: 'https://receipts.example.com/github-ent.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-03-07').toISOString(),
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Monthly subscription, auto-renewal enabled',
            createdAt: new Date('2024-03-05T10:00:00').toISOString(),
            updatedAt: new Date('2024-03-07T14:30:00').toISOString(),
        },
        {
            employeeId: 1,
            category: 'training',
            description: 'Project Management Professional (PMP) certification training',
            amount: 11500.00,
            expenseDate: new Date('2024-03-01').toISOString(),
            status: 'approved',
            receiptUrl: 'https://receipts.example.com/pmp-training.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-03-03').toISOString(),
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: '35-hour contact hours completed, exam scheduled for April',
            createdAt: new Date('2024-03-01T09:30:00').toISOString(),
            updatedAt: new Date('2024-03-03T11:00:00').toISOString(),
        },
        {
            employeeId: 2,
            category: 'supplies',
            description: 'Ergonomic office furniture - Standing desk and chair',
            amount: 8750.00,
            expenseDate: new Date('2024-03-10').toISOString(),
            status: 'approved',
            receiptUrl: 'https://receipts.example.com/furniture-inv.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-03-12').toISOString(),
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Health and wellness initiative approval',
            createdAt: new Date('2024-03-10T15:00:00').toISOString(),
            updatedAt: new Date('2024-03-12T16:45:00').toISOString(),
        },
        // Rejected expenses (3)
        {
            employeeId: 3,
            category: 'entertainment',
            description: 'Team outing expenses - Weekend trip to Goa',
            amount: 15000.00,
            expenseDate: new Date('2024-01-20').toISOString(),
            status: 'rejected',
            receiptUrl: 'https://receipts.example.com/goa-trip.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-01-25').toISOString(),
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Rejected - Exceeds team outing budget limit of 10000',
            createdAt: new Date('2024-01-20T12:00:00').toISOString(),
            updatedAt: new Date('2024-01-25T10:00:00').toISOString(),
        },
        {
            employeeId: 4,
            category: 'food',
            description: 'Personal dinner expense claimed as business meal',
            amount: 2500.00,
            expenseDate: new Date('2024-01-15').toISOString(),
            status: 'rejected',
            receiptUrl: null,
            approverId: 'user_123',
            approvalDate: new Date('2024-01-18').toISOString(),
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Rejected - No business justification provided',
            createdAt: new Date('2024-01-15T21:30:00').toISOString(),
            updatedAt: new Date('2024-01-18T09:15:00').toISOString(),
        },
        {
            employeeId: 5,
            category: 'travel',
            description: 'First-class flight tickets to Singapore',
            amount: 14800.00,
            expenseDate: new Date('2024-01-10').toISOString(),
            status: 'rejected',
            receiptUrl: 'https://receipts.example.com/singapore-flight.pdf',
            approverId: 'user_123',
            approvalDate: new Date('2024-01-12').toISOString(),
            reimbursementStatus: 'pending',
            reimbursementDate: null,
            notes: 'Rejected - Company policy allows economy class only',
            createdAt: new Date('2024-01-10T08:00:00').toISOString(),
            updatedAt: new Date('2024-01-12T13:30:00').toISOString(),
        },
    ];

    await db.insert(expenses).values(sampleExpenses);
    
    console.log('✅ Expenses seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});