import { db } from '@/db';
import { leads } from '@/db/schema';

async function main() {
    const sampleLeads = [
        // New stage - 4 leads
        {
            name: 'TechVision Solutions',
            email: 'contact@techvision.in',
            phone: '+91 98765 43210',
            source: 'website',
            stage: 'new',
            value: 850000,
            priority: 'high',
            notes: 'Interested in enterprise software solution. Company has 200+ employees and looking for complete digital transformation.',
            nextFollowUp: new Date('2024-12-28').toISOString(),
            createdAt: new Date('2024-12-25').toISOString(),
            updatedAt: new Date('2024-12-25').toISOString(),
        },
        {
            name: 'HealthCare Plus Hospitals',
            email: 'admin@healthcareplus.com',
            phone: '+91 99887 76655',
            source: 'referral',
            stage: 'new',
            value: 1250000,
            priority: 'medium',
            notes: 'Multi-location hospital chain looking for patient management system. Referral from existing client.',
            nextFollowUp: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-12-26').toISOString(),
            updatedAt: new Date('2024-12-26').toISOString(),
        },
        {
            name: 'RetailPro India',
            email: 'info@retailpro.in',
            phone: '+91 98123 45678',
            source: 'LinkedIn',
            stage: 'new',
            value: 450000,
            priority: 'low',
            notes: 'Retail chain with 15 stores. Inquired about inventory management solution.',
            nextFollowUp: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-24').toISOString(),
            updatedAt: new Date('2024-12-24').toISOString(),
        },
        {
            name: 'Global Manufacturing Ltd',
            email: 'procurement@globalmanuf.com',
            phone: '+91 97654 32109',
            source: 'trade show',
            stage: 'new',
            value: 2100000,
            priority: 'high',
            notes: 'Met at India Manufacturing Expo 2024. Large manufacturer looking for ERP solution.',
            nextFollowUp: new Date('2024-12-27').toISOString(),
            createdAt: new Date('2024-12-23').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },

        // Contacted stage - 5 leads
        {
            name: 'FinanceHub Solutions',
            email: 'director@financehub.in',
            phone: '+91 98234 56789',
            source: 'cold call',
            stage: 'contacted',
            value: 750000,
            priority: 'medium',
            notes: 'Initial call completed. Interested in accounting software. Scheduled demo for next week.',
            nextFollowUp: new Date('2025-01-03').toISOString(),
            createdAt: new Date('2024-12-15').toISOString(),
            updatedAt: new Date('2024-12-22').toISOString(),
        },
        {
            name: 'EduTech Academy',
            email: 'principal@edutech.ac.in',
            phone: '+91 99123 45678',
            source: 'website',
            stage: 'contacted',
            value: 320000,
            priority: 'medium',
            notes: 'Educational institution with 500+ students. Looking for learning management system.',
            nextFollowUp: new Date('2024-12-20').toISOString(),
            createdAt: new Date('2024-12-10').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            name: 'Logistics Express',
            email: 'operations@logisticsexpress.in',
            phone: '+91 98765 12345',
            source: 'email campaign',
            stage: 'contacted',
            value: 950000,
            priority: 'high',
            notes: 'Fleet management company. Responded to email campaign. Needs tracking and route optimization.',
            nextFollowUp: new Date('2024-12-26').toISOString(),
            createdAt: new Date('2024-12-12').toISOString(),
            updatedAt: new Date('2024-12-21').toISOString(),
        },
        {
            name: 'FoodHub Restaurant Chain',
            email: 'owner@foodhub.in',
            phone: '+91 97234 56789',
            source: 'referral',
            stage: 'contacted',
            value: 380000,
            priority: 'low',
            notes: '8 restaurant locations. Looking for POS and kitchen management system.',
            nextFollowUp: new Date('2025-01-02').toISOString(),
            createdAt: new Date('2024-12-08').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },
        {
            name: 'PropTech Realty',
            email: 'manager@proptech.com',
            phone: '+91 98876 54321',
            source: 'LinkedIn',
            stage: 'contacted',
            value: 680000,
            priority: 'medium',
            notes: 'Real estate agency managing 100+ properties. Needs property management software.',
            nextFollowUp: new Date('2024-12-31').toISOString(),
            createdAt: new Date('2024-12-14').toISOString(),
            updatedAt: new Date('2024-12-23').toISOString(),
        },

        // Proposal stage - 4 leads
        {
            name: 'AutoMart India',
            email: 'ceo@automart.in',
            phone: '+91 99876 54321',
            source: 'trade show',
            stage: 'proposal',
            value: 1450000,
            priority: 'high',
            notes: 'Automotive dealership chain. Proposal sent for CRM and inventory system. Awaiting decision.',
            nextFollowUp: new Date('2025-01-05').toISOString(),
            createdAt: new Date('2024-11-20').toISOString(),
            updatedAt: new Date('2024-12-18').toISOString(),
        },
        {
            name: 'PharmaCare Distribution',
            email: 'director@pharmacare.com',
            phone: '+91 98123 67890',
            source: 'website',
            stage: 'proposal',
            value: 890000,
            priority: 'high',
            notes: 'Pharma distribution company. Custom proposal for supply chain management sent.',
            nextFollowUp: new Date('2024-12-29').toISOString(),
            createdAt: new Date('2024-11-25').toISOString(),
            updatedAt: new Date('2024-12-19').toISOString(),
        },
        {
            name: 'SmartHome Technologies',
            email: 'sales@smarthome.in',
            phone: '+91 97123 45678',
            source: 'cold call',
            stage: 'proposal',
            value: 520000,
            priority: 'medium',
            notes: 'IoT solutions provider. Proposal for customer portal and project management system.',
            nextFollowUp: new Date('2025-01-04').toISOString(),
            createdAt: new Date('2024-11-28').toISOString(),
            updatedAt: new Date('2024-12-17').toISOString(),
        },
        {
            name: 'EventPro Management',
            email: 'info@eventpro.in',
            phone: '+91 98234 78901',
            source: 'referral',
            stage: 'proposal',
            value: 425000,
            priority: 'medium',
            notes: 'Event management company. Proposal for booking and client management system under review.',
            nextFollowUp: new Date('2024-12-30').toISOString(),
            createdAt: new Date('2024-12-01').toISOString(),
            updatedAt: new Date('2024-12-20').toISOString(),
        },

        // Won stage - 3 leads
        {
            name: 'MegaMart Supermarkets',
            email: 'cto@megamart.in',
            phone: '+91 99234 56789',
            source: 'email campaign',
            stage: 'won',
            value: 1850000,
            priority: 'high',
            notes: 'Successfully closed! 20 supermarket chain. Complete retail management solution contract signed.',
            nextFollowUp: new Date('2025-01-15').toISOString(),
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-12-10').toISOString(),
            wonAt: new Date('2024-12-10').toISOString(),
        },
        {
            name: 'SecureBank Financial',
            email: 'it@securebank.com',
            phone: '+91 98765 09876',
            source: 'referral',
            stage: 'won',
            value: 3500000,
            priority: 'high',
            notes: 'Major win! Banking software implementation. 3-year contract signed.',
            nextFollowUp: new Date('2025-01-20').toISOString(),
            createdAt: new Date('2024-09-20').toISOString(),
            updatedAt: new Date('2024-11-30').toISOString(),
            wonAt: new Date('2024-11-30').toISOString(),
        },
        {
            name: 'ConstructPro Builders',
            email: 'admin@constructpro.in',
            phone: '+91 97654 87654',
            source: 'LinkedIn',
            stage: 'won',
            value: 1120000,
            priority: 'medium',
            notes: 'Construction company. Project management and accounting software deal closed.',
            nextFollowUp: new Date('2025-01-10').toISOString(),
            createdAt: new Date('2024-10-05').toISOString(),
            updatedAt: new Date('2024-12-05').toISOString(),
            wonAt: new Date('2024-12-05').toISOString(),
        },

        // Lost stage - 2 leads
        {
            name: 'TravelWorld Tourism',
            email: 'director@travelworld.in',
            phone: '+91 98123 98765',
            source: 'website',
            stage: 'lost',
            value: 580000,
            priority: 'medium',
            notes: 'Travel agency. Lost to competitor offering lower pricing.',
            createdAt: new Date('2024-11-10').toISOString(),
            updatedAt: new Date('2024-12-15').toISOString(),
            lostReason: 'Competitor offered 30% lower pricing. Budget constraints cited by client.',
        },
        {
            name: 'FashionHub Retail',
            email: 'owner@fashionhub.in',
            phone: '+91 99876 12345',
            source: 'trade show',
            stage: 'lost',
            value: 350000,
            priority: 'low',
            notes: 'Fashion retail chain. Decided to go with in-house development.',
            createdAt: new Date('2024-11-15').toISOString(),
            updatedAt: new Date('2024-12-12').toISOString(),
            lostReason: 'Client decided to build solution internally. Timeline was not aligned with their requirements.',
        },
    ];

    await db.insert(leads).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});