import { db } from '@/db';
import { leads } from '@/db/schema';

async function main() {
    const sampleLeads = [
        // NEW STAGE - 4 leads
        {
            name: 'TechVision Solutions',
            email: 'contact@techvision.in',
            phone: '+91-9876543210',
            source: 'website',
            stage: 'new',
            value: 450000,
            assignedTo: 'user_123',
            priority: 'high',
            notes: 'Enterprise software development company looking for ERP implementation. Initial inquiry received through website contact form.',
            nextFollowUp: new Date('2024-03-25').toISOString(),
            createdAt: new Date('2024-03-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'HealthCare Plus Hospitals',
            email: 'admin@healthcareplus.in',
            phone: '+91-9845123456',
            source: 'referral',
            stage: 'new',
            value: 1250000,
            assignedTo: 'user_456',
            priority: 'high',
            notes: 'Multi-specialty hospital chain needs hospital management system. Referred by existing client. 5 branches across Mumbai.',
            nextFollowUp: new Date('2024-03-22').toISOString(),
            createdAt: new Date('2024-03-18').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'RetailPro India',
            email: 'sales@retailpro.in',
            phone: '+91-9123456789',
            source: 'LinkedIn',
            stage: 'new',
            value: 280000,
            assignedTo: 'user_123',
            priority: 'medium',
            notes: 'Retail chain managing 15 stores. Interested in inventory management and POS system integration.',
            nextFollowUp: new Date('2024-03-28').toISOString(),
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'Global Manufacturing Ltd',
            email: 'procurement@globalmanufacturing.co.in',
            phone: '+91-9998887776',
            source: 'trade show',
            stage: 'new',
            value: 850000,
            assignedTo: 'user_789',
            priority: 'medium',
            notes: 'Manufacturing company met at Industrial Expo 2024. Interested in supply chain management solution.',
            nextFollowUp: new Date('2024-03-26').toISOString(),
            createdAt: new Date('2024-03-12').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        
        // CONTACTED STAGE - 5 leads
        {
            name: 'FinanceHub Solutions',
            email: 'director@financehub.in',
            phone: '+91-9876123450',
            source: 'cold call',
            stage: 'contacted',
            value: 650000,
            assignedTo: 'user_456',
            priority: 'high',
            notes: 'Financial services company. Had initial call, discussed their need for CRM and client management portal. Follow-up meeting scheduled.',
            nextFollowUp: new Date('2024-03-24').toISOString(),
            createdAt: new Date('2024-03-08').toISOString(),
            updatedAt: new Date('2024-03-21').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'EduTech Academy',
            email: 'info@edutechacademy.in',
            phone: '+91-9765432109',
            source: 'email campaign',
            stage: 'contacted',
            value: 380000,
            assignedTo: 'user_123',
            priority: 'medium',
            notes: 'Online education platform with 50K students. Responded to email campaign. Interested in learning management system upgrade.',
            nextFollowUp: new Date('2024-03-27').toISOString(),
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'Logistics Express Pvt Ltd',
            email: 'operations@logisticsexpress.in',
            phone: '+91-9654321098',
            source: 'website',
            stage: 'contacted',
            value: 920000,
            assignedTo: 'user_789',
            priority: 'high',
            notes: 'Logistics company managing 200+ vehicles. Discussed GPS tracking and fleet management requirements. Decision maker meeting pending.',
            nextFollowUp: new Date('2024-03-23').toISOString(),
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'FoodHub Restaurant Chain',
            email: 'ceo@foodhub.in',
            phone: '+91-9543210987',
            source: 'referral',
            stage: 'contacted',
            value: 180000,
            assignedTo: 'user_456',
            priority: 'low',
            notes: 'Restaurant chain with 8 outlets. Need restaurant management and online ordering system. Spoke with operations head.',
            nextFollowUp: new Date('2024-03-29').toISOString(),
            createdAt: new Date('2024-02-28').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'PropTech Realty Solutions',
            email: 'sales@proptech.in',
            phone: '+91-9432109876',
            source: 'LinkedIn',
            stage: 'contacted',
            value: 520000,
            assignedTo: 'user_123',
            priority: 'medium',
            notes: 'Real estate company managing 2000+ properties. Initial discussion about property management software completed.',
            nextFollowUp: new Date('2024-03-21').toISOString(),
            createdAt: new Date('2024-02-25').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        
        // PROPOSAL STAGE - 4 leads
        {
            name: 'AutoMart India',
            email: 'purchase@automart.in',
            phone: '+91-9321098765',
            source: 'trade show',
            stage: 'proposal',
            value: 1450000,
            assignedTo: 'user_789',
            priority: 'high',
            notes: 'Automobile dealership network with 25 showrooms. Proposal sent for dealership management system. Negotiating on pricing and timeline.',
            nextFollowUp: new Date('2024-03-26').toISOString(),
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'PharmaCare Distribution',
            email: 'director@pharmacare.in',
            phone: '+91-9210987654',
            source: 'website',
            stage: 'proposal',
            value: 750000,
            assignedTo: 'user_456',
            priority: 'high',
            notes: 'Pharmaceutical distributor. Proposal submitted for warehouse management and distribution tracking system. Awaiting board approval.',
            nextFollowUp: new Date('2024-03-24').toISOString(),
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'SmartHome Technologies',
            email: 'projects@smarthome.in',
            phone: '+91-9109876543',
            source: 'referral',
            stage: 'proposal',
            value: 320000,
            assignedTo: 'user_123',
            priority: 'medium',
            notes: 'IoT solutions provider. Sent proposal for customer portal and service management platform. In final review stage.',
            nextFollowUp: new Date('2024-03-28').toISOString(),
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'EventPro Management',
            email: 'admin@eventpro.in',
            phone: '+91-9098765432',
            source: 'email campaign',
            stage: 'proposal',
            value: 420000,
            assignedTo: 'user_789',
            priority: 'medium',
            notes: 'Event management company handling 100+ events annually. Proposal for event management and ticketing platform sent. Comparing with competitors.',
            nextFollowUp: new Date('2024-03-25').toISOString(),
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-03-17').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        
        // WON STAGE - 3 leads
        {
            name: 'MegaMart Supermarkets',
            email: 'it@megamart.in',
            phone: '+91-8987654321',
            source: 'cold call',
            stage: 'won',
            value: 2800000,
            assignedTo: 'user_456',
            priority: 'high',
            notes: 'Supermarket chain with 40 stores. Won deal for complete POS and inventory management system. Contract signed. Project kickoff scheduled.',
            nextFollowUp: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
            wonAt: new Date('2024-02-28').toISOString(),
            lostReason: null,
        },
        {
            name: 'SecureBank Financial Services',
            email: 'technology@securebank.in',
            phone: '+91-8876543210',
            source: 'referral',
            stage: 'won',
            value: 3500000,
            assignedTo: 'user_123',
            priority: 'high',
            notes: 'Banking institution with 80 branches. Won contract for core banking system integration and mobile banking app. Implementation phase started.',
            nextFollowUp: null,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
            wonAt: new Date('2024-02-20').toISOString(),
            lostReason: null,
        },
        {
            name: 'ConstructPro Builders',
            email: 'md@constructpro.in',
            phone: '+91-8765432109',
            source: 'LinkedIn',
            stage: 'won',
            value: 950000,
            assignedTo: 'user_789',
            priority: 'medium',
            notes: 'Construction company managing 15 ongoing projects. Deal closed for project management and billing system. Ready to start onboarding.',
            nextFollowUp: null,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
            wonAt: new Date('2024-03-05').toISOString(),
            lostReason: null,
        },
        
        // LOST STAGE - 2 leads
        {
            name: 'TravelWorld Tourism',
            email: 'info@travelworld.in',
            phone: '+91-8654321098',
            source: 'website',
            stage: 'lost',
            value: 580000,
            assignedTo: 'user_456',
            priority: 'medium',
            notes: 'Travel agency managing tours and packages. Lost deal to competitor offering lower pricing. They chose a cloud-based solution with monthly subscription.',
            nextFollowUp: null,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
            wonAt: null,
            lostReason: 'chose competitor',
        },
        {
            name: 'FashionHub Retail',
            email: 'purchase@fashionhub.in',
            phone: '+91-8543210987',
            source: 'trade show',
            stage: 'lost',
            value: 420000,
            assignedTo: 'user_123',
            priority: 'low',
            notes: 'Fashion retail chain with 12 stores. Project cancelled due to budget constraints. Economic downturn affected their expansion plans.',
            nextFollowUp: null,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
            wonAt: null,
            lostReason: 'budget constraints',
        },
    ];

    await db.insert(leads).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});