import { db } from '@/db';
import { leads } from '@/db/schema';

async function main() {
    const sampleLeads = [
        // NEW STAGE (4 leads)
        {
            name: 'TechVision Solutions Pvt Ltd',
            email: 'contact@techvisionsolutions.co.in',
            phone: '+91 98765 43210',
            source: 'website',
            stage: 'new',
            value: 850000,
            assignedTo: 1,
            priority: 'medium',
            notes: 'Interested in enterprise software development services. Looking for a team to build their inventory management system.',
            nextFollowUp: new Date('2024-12-28T10:00:00Z').toISOString(),
            createdAt: new Date('2024-12-24T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-24T09:15:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'HealthCare Plus Hospitals',
            email: 'admin@healthcareplus.in',
            phone: '+91 98123 45678',
            source: 'referral',
            stage: 'new',
            value: 1250000,
            assignedTo: 2,
            priority: 'high',
            notes: 'Hospital chain looking to implement a comprehensive patient management system across 5 locations.',
            nextFollowUp: new Date('2024-12-27T14:30:00Z').toISOString(),
            createdAt: new Date('2024-12-23T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-23T11:30:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'RetailPro India',
            email: 'info@retailproindia.com',
            phone: '+91 99887 76543',
            source: 'LinkedIn',
            stage: 'new',
            value: 450000,
            assignedTo: 1,
            priority: 'low',
            notes: 'Retail chain exploring POS system integration. Currently using legacy system, considering upgrade.',
            nextFollowUp: new Date('2024-12-30T11:00:00Z').toISOString(),
            createdAt: new Date('2024-12-25T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-25T16:45:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'EduTech Learning Solutions',
            email: 'contact@edutechlearning.in',
            phone: '+91 97654 32109',
            source: 'cold call',
            stage: 'new',
            value: 680000,
            assignedTo: null,
            priority: 'medium',
            notes: 'EdTech startup needs mobile app development for their online learning platform. Target audience is college students.',
            nextFollowUp: new Date('2024-12-29T15:00:00Z').toISOString(),
            createdAt: new Date('2024-12-26T10:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-26T10:20:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        // CONTACTED STAGE (5 leads)
        {
            name: 'FinanceHub Solutions',
            email: 'info@financehub.co.in',
            phone: '+91 98765 12345',
            source: 'email campaign',
            stage: 'contacted',
            value: 1850000,
            assignedTo: 2,
            priority: 'high',
            notes: 'Financial services company requiring secure banking software. Had initial discussion about their requirements. They need SEBI compliance features.',
            nextFollowUp: new Date('2025-01-02T10:30:00Z').toISOString(),
            createdAt: new Date('2024-12-10T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-22T09:15:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'LogiTrack Warehousing Pvt Ltd',
            email: 'operations@logitrack.in',
            phone: '+91 97123 45678',
            source: 'trade show',
            stage: 'contacted',
            value: 950000,
            assignedTo: 1,
            priority: 'medium',
            notes: 'Met at Mumbai Tech Expo. Warehouse management company needs IoT integration for inventory tracking. Sent initial proposal deck.',
            nextFollowUp: new Date('2025-01-03T14:00:00Z').toISOString(),
            createdAt: new Date('2024-12-05T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-21T16:45:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'GreenEnergy Consultants',
            email: 'contact@greenenergy.co.in',
            phone: '+91 98456 78901',
            source: 'referral',
            stage: 'contacted',
            value: 720000,
            assignedTo: 2,
            priority: 'medium',
            notes: 'Renewable energy consulting firm needs customer portal and project management tool. Referred by existing client TechVision.',
            nextFollowUp: new Date('2025-01-04T11:30:00Z').toISOString(),
            createdAt: new Date('2024-12-08T09:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-23T10:30:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'FoodMart Express',
            email: 'business@foodmartexpress.in',
            phone: '+91 99876 54321',
            source: 'website',
            stage: 'contacted',
            value: 540000,
            assignedTo: 1,
            priority: 'low',
            notes: 'Food delivery startup exploring custom mobile app development. Competition with existing players, price-sensitive.',
            nextFollowUp: new Date('2025-01-05T15:30:00Z').toISOString(),
            createdAt: new Date('2024-12-12T13:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-24T11:15:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'AutoParts Hub India',
            email: 'sales@autopartshub.co.in',
            phone: '+91 96543 21098',
            source: 'LinkedIn',
            stage: 'contacted',
            value: 890000,
            assignedTo: null,
            priority: 'medium',
            notes: 'Automobile parts distributor needs e-commerce platform with B2B features. Had product demo last week, awaiting feedback.',
            nextFollowUp: new Date('2025-01-06T10:00:00Z').toISOString(),
            createdAt: new Date('2024-12-15T15:10:00Z').toISOString(),
            updatedAt: new Date('2024-12-25T14:20:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        // PROPOSAL STAGE (4 leads)
        {
            name: 'MediCare Diagnostics',
            email: 'director@medicarediagnostics.in',
            phone: '+91 98234 56789',
            source: 'cold call',
            stage: 'proposal',
            value: 1650000,
            assignedTo: 2,
            priority: 'high',
            notes: 'Diagnostic center chain needs lab management system with NABL compliance. Proposal sent including integration with existing equipment. Decision expected by end of January.',
            nextFollowUp: new Date('2025-01-08T11:00:00Z').toISOString(),
            createdAt: new Date('2024-11-20T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-20T15:30:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'PropTech Realty Solutions',
            email: 'info@proptechrealty.co.in',
            phone: '+91 97345 67890',
            source: 'referral',
            stage: 'proposal',
            value: 2150000,
            assignedTo: 1,
            priority: 'high',
            notes: 'Real estate company needs CRM and property listing platform. Custom proposal prepared with 3D virtual tour features. Very interested, pricing negotiation ongoing.',
            nextFollowUp: new Date('2025-01-10T14:30:00Z').toISOString(),
            createdAt: new Date('2024-11-15T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-22T10:45:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'TextileManufacturing Co',
            email: 'production@textilemanufacturing.in',
            phone: '+91 98876 54321',
            source: 'trade show',
            stage: 'proposal',
            value: 1320000,
            assignedTo: 2,
            priority: 'medium',
            notes: 'Textile manufacturer needs production tracking and inventory management system. Proposal includes IoT sensors for machine monitoring. Waiting for board approval.',
            nextFollowUp: new Date('2025-01-12T10:30:00Z').toISOString(),
            createdAt: new Date('2024-11-25T14:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-23T09:20:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        {
            name: 'TravelEase Tours & Travels',
            email: 'booking@traveleasetoursltd.in',
            phone: '+91 99123 45678',
            source: 'email campaign',
            stage: 'proposal',
            value: 780000,
            assignedTo: 1,
            priority: 'medium',
            notes: 'Travel agency needs booking management system with payment gateway integration. Proposal sent with mobile app option. Price-conscious but quality-focused.',
            nextFollowUp: new Date('2025-01-15T15:00:00Z').toISOString(),
            createdAt: new Date('2024-12-01T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-24T16:30:00Z').toISOString(),
            wonAt: null,
            lostReason: null,
        },
        // WON STAGE (3 leads)
        {
            name: 'SmartLogistics Express',
            email: 'operations@smartlogistics.co.in',
            phone: '+91 98567 89012',
            source: 'website',
            stage: 'won',
            value: 2850000,
            assignedTo: 2,
            priority: 'high',
            notes: 'Logistics company signed contract for comprehensive fleet management and tracking system. Project kickoff scheduled for January 15th.',
            nextFollowUp: null,
            createdAt: new Date('2024-10-15T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-18T14:20:00Z').toISOString(),
            wonAt: new Date('2024-12-18T14:20:00Z').toISOString(),
            lostReason: null,
        },
        {
            name: 'FashionRetail Boutique Chain',
            email: 'management@fashionretail.in',
            phone: '+91 97234 56789',
            source: 'referral',
            stage: 'won',
            value: 1580000,
            assignedTo: 1,
            priority: 'high',
            notes: 'Fashion retail chain awarded contract for e-commerce platform with omnichannel capabilities. Development started December 10th.',
            nextFollowUp: null,
            createdAt: new Date('2024-10-20T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-15T11:45:00Z').toISOString(),
            wonAt: new Date('2024-12-15T11:45:00Z').toISOString(),
            lostReason: null,
        },
        {
            name: 'ConstructTech Builders',
            email: 'projects@constructtech.co.in',
            phone: '+91 98901 23456',
            source: 'LinkedIn',
            stage: 'won',
            value: 1920000,
            assignedTo: 2,
            priority: 'high',
            notes: 'Construction company signed for project management and site tracking system. Contract includes drone integration for site monitoring.',
            nextFollowUp: null,
            createdAt: new Date('2024-11-01T13:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-20T10:30:00Z').toISOString(),
            wonAt: new Date('2024-12-20T10:30:00Z').toISOString(),
            lostReason: null,
        },
        // LOST STAGE (2 leads)
        {
            name: 'BudgetStay Hotels',
            email: 'management@budgetstayhotels.in',
            phone: '+91 96789 01234',
            source: 'cold call',
            stage: 'lost',
            value: 920000,
            assignedTo: 1,
            priority: 'low',
            notes: 'Hotel chain was interested in property management system but decided to go with established vendor offering lower pricing.',
            nextFollowUp: null,
            createdAt: new Date('2024-11-05T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-12T15:20:00Z').toISOString(),
            wonAt: null,
            lostReason: 'Budget constraints - chose competitor with lower pricing',
        },
        {
            name: 'PharmaCare Distributors',
            email: 'procurement@pharmacare.co.in',
            phone: '+91 95678 90123',
            source: 'trade show',
            stage: 'lost',
            value: 1150000,
            assignedTo: 2,
            priority: 'medium',
            notes: 'Pharmaceutical distributor needed inventory and compliance management system. Lost to competitor who had existing pharma industry experience.',
            nextFollowUp: null,
            createdAt: new Date('2024-10-28T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-08T09:15:00Z').toISOString(),
            wonAt: null,
            lostReason: 'Chose competitor with specialized pharma industry expertise',
        },
    ];

    await db.insert(leads).values(sampleLeads);
    
    console.log('✅ Leads seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});