import { db } from '@/db';
import { projects } from '@/db/schema';

async function main() {
    const sampleProjects = [
        {
            name: 'ERP System Implementation',
            description: 'Complete implementation of enterprise resource planning system to streamline business operations, inventory management, and financial reporting across all departments.',
            clientId: 3,
            contractId: 2,
            status: 'in_progress',
            startDate: new Date('2024-01-15').toISOString(),
            endDate: new Date('2024-09-30').toISOString(),
            budget: 5500000,
            spent: 2750000,
            projectManager: 1,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            name: 'Mobile Banking App Development',
            description: 'Development of secure mobile banking application for iOS and Android platforms with features including account management, fund transfers, bill payments, and investment tracking.',
            clientId: 7,
            contractId: 5,
            status: 'in_progress',
            startDate: new Date('2024-02-01').toISOString(),
            endDate: new Date('2024-08-31').toISOString(),
            budget: 8000000,
            spent: 4800000,
            projectManager: 2,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
        {
            name: 'Cloud Infrastructure Migration',
            description: 'Migration of on-premise infrastructure to AWS cloud platform including server setup, database migration, security configuration, and load balancing implementation.',
            clientId: 1,
            contractId: 1,
            status: 'in_progress',
            startDate: new Date('2024-03-01').toISOString(),
            endDate: new Date('2024-07-31').toISOString(),
            budget: 3200000,
            spent: 1600000,
            projectManager: 1,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-03-20').toISOString(),
        },
        {
            name: 'E-commerce Platform Modernization',
            description: 'Complete overhaul of existing e-commerce platform with modern UI/UX, payment gateway integration, inventory management, and analytics dashboard implementation.',
            clientId: 5,
            contractId: null,
            status: 'in_progress',
            startDate: new Date('2024-02-15').toISOString(),
            endDate: new Date('2024-10-31').toISOString(),
            budget: 6500000,
            spent: 3900000,
            projectManager: null,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-03-19').toISOString(),
        },
        {
            name: 'AI-Powered Customer Support System',
            description: 'Development and integration of AI-powered chatbot and ticketing system to enhance customer support capabilities with natural language processing and automated response generation.',
            clientId: 9,
            contractId: 7,
            status: 'planning',
            startDate: new Date('2024-04-01').toISOString(),
            endDate: new Date('2024-11-30').toISOString(),
            budget: 4500000,
            spent: 225000,
            projectManager: 2,
            createdAt: new Date('2024-03-10').toISOString(),
            updatedAt: new Date('2024-03-21').toISOString(),
        },
        {
            name: 'Supply Chain Management System',
            description: 'Implementation of comprehensive supply chain management solution with real-time tracking, vendor management, procurement automation, and predictive analytics for inventory optimization.',
            clientId: 4,
            contractId: null,
            status: 'planning',
            startDate: new Date('2024-05-01').toISOString(),
            endDate: new Date('2025-02-28').toISOString(),
            budget: 7200000,
            spent: 360000,
            projectManager: 1,
            createdAt: new Date('2024-03-15').toISOString(),
            updatedAt: new Date('2024-03-22').toISOString(),
        },
        {
            name: 'Data Analytics Dashboard Implementation',
            description: 'Successful deployment of comprehensive business intelligence and analytics dashboard with real-time data visualization, custom reporting, and predictive analytics capabilities.',
            clientId: 2,
            contractId: 3,
            status: 'completed',
            startDate: new Date('2023-09-01').toISOString(),
            endDate: new Date('2024-02-29').toISOString(),
            budget: 2800000,
            spent: 2660000,
            projectManager: 2,
            createdAt: new Date('2023-08-20').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            name: 'Cybersecurity Infrastructure Upgrade',
            description: 'Comprehensive upgrade of cybersecurity infrastructure including firewall implementation, intrusion detection systems, security audit, and employee training program. Currently on hold pending budget approval.',
            clientId: 8,
            contractId: 6,
            status: 'on_hold',
            startDate: new Date('2024-01-20').toISOString(),
            endDate: new Date('2024-06-30').toISOString(),
            budget: 3800000,
            spent: 950000,
            projectManager: null,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
    ];

    await db.insert(projects).values(sampleProjects);
    
    console.log('✅ Projects seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});