import { db } from '@/db';
import { proposals } from '@/db/schema';

async function main() {
    const sampleProposals = [
        {
            proposalNumber: 'PROP-2024-01-123456',
            clientId: 3,
            leadId: null,
            title: 'Digital Transformation Initiative',
            description: 'Comprehensive digital transformation program to modernize business operations and enhance customer experience through cloud migration, process automation, and data analytics implementation.',
            objective: 'Transform legacy systems into modern cloud-based infrastructure, reduce operational costs by 30%, and improve customer satisfaction scores by 25% within 12 months.',
            scopeOfWork: 'Phase 1: Infrastructure Assessment & Planning (4 weeks)\n- Current system audit and documentation\n- Cloud architecture design\n- Migration strategy development\n\nPhase 2: Cloud Migration (8 weeks)\n- Database migration to AWS RDS\n- Application containerization\n- CI/CD pipeline setup\n\nPhase 3: Process Automation (6 weeks)\n- Workflow automation implementation\n- Integration with existing systems\n- User training and documentation\n\nPhase 4: Analytics Implementation (6 weeks)\n- Data warehouse setup\n- Business intelligence dashboards\n- Predictive analytics models',
            deliverables: '- Complete cloud infrastructure on AWS\n- Containerized microservices architecture\n- Automated CI/CD pipelines\n- Business intelligence dashboards\n- Comprehensive documentation\n- 6 months post-implementation support',
            timeline: '24 weeks',
            pricing: 4500000,
            status: 'draft',
            templateId: 'template_enterprise',
            pdfUrl: null,
            createdBy: 1,
            sentAt: null,
            reviewedAt: null,
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-01-15T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-01-18T14:20:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-01-234567',
            clientId: null,
            leadId: 5,
            title: 'Enterprise Software Development',
            description: 'Custom enterprise resource planning (ERP) system development tailored to manufacturing operations, including inventory management, production planning, and supply chain optimization.',
            objective: 'Develop a scalable ERP solution that streamlines manufacturing operations, reduces inventory costs by 20%, and improves production efficiency by 35%.',
            scopeOfWork: 'Phase 1: Requirements Analysis (3 weeks)\n- Business process mapping\n- Technical requirements documentation\n- System architecture design\n\nPhase 2: Core Module Development (12 weeks)\n- Inventory management system\n- Production planning module\n- Supply chain management\n\nPhase 3: Integration & Testing (4 weeks)\n- Third-party system integration\n- Quality assurance testing\n- Performance optimization\n\nPhase 4: Deployment & Training (3 weeks)\n- System deployment\n- User training programs\n- Knowledge transfer',
            deliverables: '- Custom ERP system with all modules\n- Mobile applications for iOS and Android\n- API documentation\n- User manuals and training materials\n- 1 year maintenance and support',
            timeline: '22 weeks',
            pricing: 3800000,
            status: 'draft',
            templateId: 'template_001',
            pdfUrl: null,
            createdBy: 2,
            sentAt: null,
            reviewedAt: null,
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-01-20T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-01-22T16:45:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-02-345678',
            clientId: 7,
            leadId: null,
            title: 'Cloud Solutions Package',
            description: 'End-to-end cloud infrastructure setup and management services including AWS architecture, security implementation, cost optimization, and 24/7 monitoring.',
            objective: 'Establish secure and scalable cloud infrastructure with 99.9% uptime guarantee, implement best security practices, and optimize cloud costs by 40%.',
            scopeOfWork: 'Phase 1: Cloud Strategy & Planning (2 weeks)\n- Current infrastructure assessment\n- Cloud architecture design\n- Cost analysis and optimization plan\n\nPhase 2: Infrastructure Setup (6 weeks)\n- AWS account configuration\n- VPC and network setup\n- Security groups and IAM policies\n- Load balancers and auto-scaling\n\nPhase 3: Security Implementation (3 weeks)\n- Encryption at rest and in transit\n- Security monitoring and alerts\n- Compliance configuration\n\nPhase 4: Ongoing Management (Continuous)\n- 24/7 monitoring and support\n- Performance optimization\n- Regular security audits',
            deliverables: '- Fully configured AWS cloud infrastructure\n- Security compliance documentation\n- Monitoring dashboards\n- Disaster recovery plan\n- Monthly performance reports\n- 24/7 support for 12 months',
            timeline: '12 months',
            pricing: 2200000,
            status: 'sent',
            templateId: 'template_cloud',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-02-345678.pdf',
            createdBy: 1,
            sentAt: new Date('2024-02-05T11:00:00Z').toISOString(),
            reviewedAt: null,
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-02-01T08:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-05T11:00:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-02-456789',
            clientId: null,
            leadId: 12,
            title: 'E-commerce Platform Development',
            description: 'Full-featured e-commerce platform with advanced features including AI-powered product recommendations, multi-vendor support, and integrated payment gateways.',
            objective: 'Launch a modern e-commerce platform that supports 100,000+ products, handles 10,000 concurrent users, and provides seamless shopping experience across all devices.',
            scopeOfWork: 'Phase 1: Platform Foundation (4 weeks)\n- Database schema design\n- Core API development\n- Admin panel creation\n\nPhase 2: Customer Features (6 weeks)\n- Product catalog and search\n- Shopping cart and checkout\n- User account management\n- Order tracking system\n\nPhase 3: Vendor Management (4 weeks)\n- Multi-vendor dashboard\n- Inventory management\n- Analytics and reporting\n\nPhase 4: Advanced Features (4 weeks)\n- AI recommendation engine\n- Payment gateway integration\n- Mobile app development',
            deliverables: '- Complete e-commerce web platform\n- Native mobile apps (iOS & Android)\n- Admin and vendor dashboards\n- Payment gateway integrations\n- Product recommendation system\n- Documentation and training\n- 3 months support',
            timeline: '18 weeks',
            pricing: 3200000,
            status: 'sent',
            templateId: 'template_ecommerce',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-02-456789.pdf',
            createdBy: 3,
            sentAt: new Date('2024-02-10T14:30:00Z').toISOString(),
            reviewedAt: null,
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-02-06T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-02-10T14:30:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-02-567890',
            clientId: 5,
            leadId: null,
            title: 'Mobile App Development - Healthcare',
            description: 'HIPAA-compliant healthcare mobile application for patient management, telemedicine consultations, prescription tracking, and health records management.',
            objective: 'Develop a secure healthcare app that improves patient engagement, reduces appointment no-shows by 40%, and streamlines clinical workflows.',
            scopeOfWork: 'Phase 1: Compliance & Planning (3 weeks)\n- HIPAA compliance review\n- Security architecture design\n- User experience design\n\nPhase 2: Core Features Development (8 weeks)\n- Patient registration and profiles\n- Appointment scheduling system\n- Video consultation integration\n- Prescription management\n\nPhase 3: Advanced Features (4 weeks)\n- Health records integration\n- Wearable device connectivity\n- Push notifications\n- Emergency contact features\n\nPhase 4: Testing & Deployment (3 weeks)\n- Security testing\n- HIPAA compliance audit\n- App store submission',
            deliverables: '- iOS and Android native apps\n- Healthcare provider web portal\n- HIPAA compliance documentation\n- API documentation\n- Admin dashboard\n- 6 months maintenance\n- Staff training',
            timeline: '18 weeks',
            pricing: 2800000,
            status: 'sent',
            templateId: 'template_healthcare',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-02-567890.pdf',
            createdBy: 2,
            sentAt: new Date('2024-02-12T09:45:00Z').toISOString(),
            reviewedAt: null,
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-02-08T13:20:00Z').toISOString(),
            updatedAt: new Date('2024-02-12T09:45:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-01-678901',
            clientId: 2,
            leadId: null,
            title: 'Data Analytics Platform',
            description: 'Advanced data analytics and business intelligence platform with real-time dashboards, predictive modeling, and automated reporting capabilities.',
            objective: 'Implement comprehensive analytics solution that provides actionable insights, reduces reporting time by 70%, and enables data-driven decision making.',
            scopeOfWork: 'Phase 1: Data Infrastructure (4 weeks)\n- Data warehouse setup\n- ETL pipeline development\n- Data quality framework\n\nPhase 2: Analytics Development (6 weeks)\n- Real-time dashboards\n- Custom report builder\n- KPI tracking system\n\nPhase 3: Machine Learning (4 weeks)\n- Predictive models development\n- Anomaly detection system\n- Forecasting algorithms\n\nPhase 4: Deployment & Training (2 weeks)\n- System deployment\n- User training\n- Documentation',
            deliverables: '- Data warehouse infrastructure\n- Interactive BI dashboards\n- Custom reporting tools\n- ML prediction models\n- Mobile analytics app\n- Training materials\n- 9 months support',
            timeline: '16 weeks',
            pricing: 3500000,
            status: 'under_review',
            templateId: 'template_analytics',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-01-678901.pdf',
            createdBy: 1,
            sentAt: new Date('2024-01-25T10:00:00Z').toISOString(),
            reviewedAt: new Date('2024-02-02T15:30:00Z').toISOString(),
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-01-22T11:15:00Z').toISOString(),
            updatedAt: new Date('2024-02-02T15:30:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-02-789012',
            clientId: null,
            leadId: 8,
            title: 'Cybersecurity Assessment & Implementation',
            description: 'Comprehensive cybersecurity audit and implementation of security measures including penetration testing, vulnerability assessment, and security operations center setup.',
            objective: 'Strengthen cybersecurity posture, achieve ISO 27001 compliance, and reduce security incidents by 85% through proactive monitoring and threat detection.',
            scopeOfWork: 'Phase 1: Security Audit (3 weeks)\n- Infrastructure assessment\n- Penetration testing\n- Vulnerability scanning\n- Compliance gap analysis\n\nPhase 2: Security Implementation (8 weeks)\n- Firewall and IDS/IPS setup\n- SIEM implementation\n- Endpoint protection deployment\n- Security policy development\n\nPhase 3: SOC Setup (4 weeks)\n- Security monitoring center\n- Incident response procedures\n- Threat intelligence integration\n\nPhase 4: Training & Documentation (2 weeks)\n- Security awareness training\n- Procedure documentation\n- Compliance reporting',
            deliverables: '- Security audit report\n- Implemented security infrastructure\n- SOC monitoring system\n- Security policies and procedures\n- Incident response playbooks\n- Staff training program\n- 12 months managed security services',
            timeline: '17 weeks',
            pricing: 2600000,
            status: 'under_review',
            templateId: 'template_security',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-02-789012.pdf',
            createdBy: 3,
            sentAt: new Date('2024-02-08T13:00:00Z').toISOString(),
            reviewedAt: new Date('2024-02-15T10:20:00Z').toISOString(),
            acceptedAt: null,
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-02-04T09:00:00Z').toISOString(),
            updatedAt: new Date('2024-02-15T10:20:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-01-890123',
            clientId: 9,
            leadId: null,
            title: 'AI-Powered Customer Service Platform',
            description: 'Intelligent customer service platform with AI chatbot, sentiment analysis, automated ticket routing, and omnichannel support across email, chat, and social media.',
            objective: 'Reduce customer service response time by 60%, improve customer satisfaction by 45%, and handle 3x more inquiries with the same team size.',
            scopeOfWork: 'Phase 1: AI Model Development (5 weeks)\n- Natural language processing setup\n- Chatbot training\n- Intent recognition models\n- Sentiment analysis implementation\n\nPhase 2: Platform Development (7 weeks)\n- Omnichannel integration\n- Ticket management system\n- Knowledge base creation\n- Automated routing engine\n\nPhase 3: Integration & Testing (3 weeks)\n- CRM integration\n- Live chat implementation\n- Email system integration\n- Performance testing\n\nPhase 4: Launch & Optimization (2 weeks)\n- System deployment\n- Team training\n- Continuous learning setup',
            deliverables: '- AI chatbot with NLP capabilities\n- Omnichannel support platform\n- Knowledge base system\n- Analytics dashboard\n- CRM integrations\n- Training materials\n- 12 months AI model optimization',
            timeline: 'Q2 2024',
            pricing: 3100000,
            status: 'accepted',
            templateId: 'template_ai',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-01-890123.pdf',
            createdBy: 2,
            sentAt: new Date('2024-01-18T11:30:00Z').toISOString(),
            reviewedAt: new Date('2024-01-25T14:00:00Z').toISOString(),
            acceptedAt: new Date('2024-02-01T10:15:00Z').toISOString(),
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-01-12T10:00:00Z').toISOString(),
            updatedAt: new Date('2024-02-01T10:15:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-01-901234',
            clientId: 6,
            leadId: null,
            title: 'Supply Chain Management System',
            description: 'End-to-end supply chain management solution with real-time tracking, inventory optimization, vendor management, and predictive demand forecasting.',
            objective: 'Optimize supply chain operations, reduce inventory costs by 25%, improve delivery times by 35%, and enhance supplier collaboration.',
            scopeOfWork: 'Phase 1: System Architecture (3 weeks)\n- Requirements analysis\n- Database design\n- Integration planning\n\nPhase 2: Core Modules (8 weeks)\n- Inventory management\n- Order processing\n- Warehouse management\n- Vendor portal\n\nPhase 3: Advanced Features (5 weeks)\n- Real-time tracking integration\n- Demand forecasting AI\n- Route optimization\n- Automated reordering\n\nPhase 4: Integration & Training (3 weeks)\n- ERP integration\n- Logistics partner APIs\n- User training\n- Documentation',
            deliverables: '- Complete SCM platform\n- Vendor and warehouse portals\n- Mobile tracking apps\n- Predictive analytics dashboards\n- Integration with existing systems\n- Comprehensive documentation\n- 8 months support and updates',
            timeline: '19 weeks',
            pricing: 2900000,
            status: 'accepted',
            templateId: 'template_scm',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-01-901234.pdf',
            createdBy: 1,
            sentAt: new Date('2024-01-22T09:00:00Z').toISOString(),
            reviewedAt: new Date('2024-01-28T16:45:00Z').toISOString(),
            acceptedAt: new Date('2024-02-05T11:30:00Z').toISOString(),
            rejectedAt: null,
            rejectionReason: null,
            createdAt: new Date('2024-01-16T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-05T11:30:00Z').toISOString(),
        },
        {
            proposalNumber: 'PROP-2024-02-012345',
            clientId: null,
            leadId: 15,
            title: 'Blockchain-Based Asset Tracking',
            description: 'Innovative blockchain solution for transparent and immutable asset tracking, providing end-to-end supply chain visibility and automated compliance reporting.',
            objective: 'Implement blockchain technology to ensure 100% supply chain transparency, reduce fraud by 95%, and automate compliance documentation.',
            scopeOfWork: 'Phase 1: Blockchain Setup (4 weeks)\n- Blockchain architecture design\n- Smart contract development\n- Node deployment\n\nPhase 2: Platform Development (10 weeks)\n- Asset tracking interface\n- QR code integration\n- Mobile scanning apps\n- Web portal development\n\nPhase 3: Integration (4 weeks)\n- Legacy system integration\n- IoT sensor connectivity\n- API development\n\nPhase 4: Testing & Launch (3 weeks)\n- Security audit\n- Performance testing\n- Pilot program\n- Full deployment',
            deliverables: '- Blockchain infrastructure\n- Smart contracts for asset tracking\n- Web and mobile applications\n- IoT integration system\n- Real-time tracking dashboards\n- Compliance reporting tools\n- Documentation and training\n- 6 months support',
            timeline: '21 weeks',
            pricing: 5000000,
            status: 'rejected',
            templateId: 'template_blockchain',
            pdfUrl: 'https://storage.example.com/proposals/PROP-2024-02-012345.pdf',
            createdBy: 3,
            sentAt: new Date('2024-02-01T10:00:00Z').toISOString(),
            reviewedAt: new Date('2024-02-10T14:30:00Z').toISOString(),
            acceptedAt: null,
            rejectedAt: new Date('2024-02-14T11:00:00Z').toISOString(),
            rejectionReason: 'Budget exceeded - requested 40% cost reduction which is not feasible while maintaining quality standards. Lead mentioned they will reconsider in Q3 2024 with increased budget allocation.',
            createdAt: new Date('2024-01-28T11:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-14T11:00:00Z').toISOString(),
        },
    ];

    await db.insert(proposals).values(sampleProposals);
    
    console.log('✅ Proposals seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});