import { db } from '@/db';
import { quotations } from '@/db/schema';

function generateQuotationNumber(month: number, sequence: number): string {
    const monthStr = month.toString().padStart(2, '0');
    const seqStr = sequence.toString().padStart(6, '0');
    return `QUO-2024-${monthStr}-${seqStr}`;
}

async function main() {
    const sampleQuotations = [
        {
            quotationNumber: generateQuotationNumber(1, 123456),
            clientId: 1,
            leadId: null,
            title: 'Website Development Services',
            description: 'Complete website development including responsive design, CMS integration, and SEO optimization.',
            subtotal: 500000,
            taxRate: 18.0,
            taxAmount: 90000,
            totalAmount: 590000,
            validUntil: new Date('2024-04-30').toISOString(),
            status: 'draft',
            notes: 'Please review the scope and timeline. Payment terms: 30% advance, 70% on completion.',
            termsConditions: 'All prices are in INR. Validity: 30 days from quotation date. Payment terms as per agreement.',
            createdBy: 1,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(1, 234567),
            clientId: null,
            leadId: 5,
            title: 'Cloud Migration Package',
            description: 'Complete migration of on-premise infrastructure to AWS cloud with setup, configuration, and training.',
            subtotal: 1500000,
            taxRate: 18.0,
            taxAmount: 270000,
            totalAmount: 1770000,
            validUntil: new Date('2024-05-15').toISOString(),
            status: 'sent',
            notes: 'Includes 3 months post-migration support. Server costs not included.',
            termsConditions: 'All prices are in INR. Validity: 45 days. 40% advance, 30% mid-project, 30% on completion.',
            createdBy: 2,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(1, 345678),
            clientId: 3,
            leadId: null,
            title: 'Annual Support Plan - Premium',
            description: '24/7 technical support with 4-hour response time, quarterly system audits, and priority feature requests.',
            subtotal: 800000,
            taxRate: 18.0,
            taxAmount: 144000,
            totalAmount: 944000,
            validUntil: new Date('2024-04-15').toISOString(),
            status: 'draft',
            notes: 'Annual contract with quarterly billing option available.',
            termsConditions: 'Contract period: 12 months. Auto-renewal unless cancelled 60 days before expiry.',
            createdBy: 1,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 456789),
            clientId: null,
            leadId: 8,
            title: 'Mobile App Development - iOS & Android',
            description: 'Native mobile application development for iOS and Android platforms with backend API integration.',
            subtotal: 2000000,
            taxRate: 18.0,
            taxAmount: 360000,
            totalAmount: 2360000,
            validUntil: new Date('2024-05-30').toISOString(),
            status: 'sent',
            notes: 'Development timeline: 4 months. Client to provide design assets and content.',
            termsConditions: 'All prices are in INR. Validity: 60 days. Payment in 4 milestones.',
            createdBy: 2,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 567890),
            clientId: 5,
            leadId: null,
            title: 'Digital Marketing Campaign - Q2 2024',
            description: 'Comprehensive digital marketing services including SEO, PPC, social media management, and content creation.',
            subtotal: 350000,
            taxRate: 18.0,
            taxAmount: 63000,
            totalAmount: 413000,
            validUntil: new Date('2024-03-31').toISOString(),
            status: 'accepted',
            notes: 'Campaign duration: 3 months (Apr-Jun 2024). Monthly reporting included.',
            termsConditions: 'Monthly billing. Minimum commitment: 3 months. Ad spend not included in quoted price.',
            createdBy: 1,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
            acceptedAt: new Date('2024-02-12').toISOString(),
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 678901),
            clientId: null,
            leadId: 12,
            title: 'Enterprise CRM Implementation',
            description: 'Salesforce CRM implementation with customization, data migration, and user training.',
            subtotal: 1800000,
            taxRate: 18.0,
            taxAmount: 324000,
            totalAmount: 2124000,
            validUntil: new Date('2024-06-15').toISOString(),
            status: 'sent',
            notes: 'Implementation timeline: 3 months. Includes 6 months post-implementation support.',
            termsConditions: 'All prices are in INR. Salesforce licenses to be procured separately by client.',
            createdBy: 2,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 789012),
            clientId: 7,
            leadId: null,
            title: 'Cybersecurity Audit and Consultation',
            description: 'Comprehensive security assessment, vulnerability testing, and security roadmap development.',
            subtotal: 450000,
            taxRate: 18.0,
            taxAmount: 81000,
            totalAmount: 531000,
            validUntil: new Date('2024-04-20').toISOString(),
            status: 'accepted',
            notes: 'Audit duration: 2 weeks. Final report with recommendations within 1 week of completion.',
            termsConditions: 'All findings confidential. 50% advance, 50% on report delivery.',
            createdBy: 1,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
            acceptedAt: new Date('2024-02-18').toISOString(),
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 890123),
            clientId: null,
            leadId: 15,
            title: 'E-commerce Platform Development',
            description: 'Custom e-commerce platform with payment gateway integration, inventory management, and admin panel.',
            subtotal: 1200000,
            taxRate: 18.0,
            taxAmount: 216000,
            totalAmount: 1416000,
            validUntil: new Date('2024-05-10').toISOString(),
            status: 'sent',
            notes: 'Development timeline: 3 months. Client to provide product catalog and payment gateway credentials.',
            termsConditions: 'Payment gateway fees not included. Hosting and domain to be arranged by client.',
            createdBy: 2,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 901234),
            clientId: 9,
            leadId: null,
            title: 'Data Analytics Dashboard Development',
            description: 'Interactive business intelligence dashboard with real-time data visualization and reporting capabilities.',
            subtotal: 650000,
            taxRate: 18.0,
            taxAmount: 117000,
            totalAmount: 767000,
            validUntil: new Date('2024-01-30').toISOString(),
            status: 'expired',
            notes: 'Dashboard to integrate with existing database. Training for 5 users included.',
            termsConditions: 'Database access credentials required. Support period: 6 months post-deployment.',
            createdBy: 1,
            createdAt: new Date('2023-12-20').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 12345),
            clientId: null,
            leadId: 18,
            title: 'API Development and Integration Services',
            description: 'RESTful API development with third-party service integrations and comprehensive documentation.',
            subtotal: 550000,
            taxRate: 0.0,
            taxAmount: 0,
            totalAmount: 550000,
            validUntil: new Date('2024-04-25').toISOString(),
            status: 'draft',
            notes: 'Export of services - GST exempt. Timeline: 6 weeks.',
            termsConditions: 'International client - payments in USD equivalent. Source code ownership upon full payment.',
            createdBy: 2,
            createdAt: new Date('2024-02-20').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
            acceptedAt: null,
            rejectedReason: null,
        },
        {
            quotationNumber: generateQuotationNumber(2, 23456),
            clientId: 4,
            leadId: null,
            title: 'IT Infrastructure Upgrade',
            description: 'Complete network infrastructure upgrade including servers, switches, and security appliances.',
            subtotal: 1750000,
            taxRate: 18.0,
            taxAmount: 315000,
            totalAmount: 2065000,
            validUntil: new Date('2024-03-28').toISOString(),
            status: 'rejected',
            notes: 'Hardware procurement and installation included. 1-year warranty on all equipment.',
            termsConditions: 'Equipment warranties as per manufacturer terms. Installation timeline: 2 weeks.',
            createdBy: 1,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
            acceptedAt: null,
            rejectedReason: 'Client opted for a phased approach instead of complete upgrade. Budget constraints cited.',
        },
        {
            quotationNumber: generateQuotationNumber(2, 34567),
            clientId: 10,
            leadId: null,
            title: 'Custom Software Development - Inventory Management',
            description: 'Tailored inventory management system with barcode scanning, reporting, and multi-location support.',
            subtotal: 950000,
            taxRate: 18.0,
            taxAmount: 171000,
            totalAmount: 1121000,
            validUntil: new Date('2024-05-05').toISOString(),
            status: 'accepted',
            notes: 'Development timeline: 10 weeks. Includes 3 rounds of revisions and user acceptance testing.',
            termsConditions: 'Source code ownership transferred upon final payment. 1-year maintenance included.',
            createdBy: 2,
            createdAt: new Date('2024-02-22').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
            acceptedAt: new Date('2024-02-28').toISOString(),
            rejectedReason: null,
        },
    ];

    await db.insert(quotations).values(sampleQuotations);
    
    console.log('✅ Quotations seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});