import { db } from '@/db';
import { slas } from '@/db/schema';

async function main() {
    const sampleSLAs = [
        {
            clientId: 1,
            contractId: 1,
            metricName: 'Response Time',
            targetValue: '< 4 hours',
            currentValue: '< 3 hours',
            status: 'met',
            measurementPeriod: 'daily',
            lastMeasuredAt: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            clientId: 2,
            contractId: 2,
            metricName: 'System Uptime',
            targetValue: '99.9% uptime',
            currentValue: '99.95% uptime',
            status: 'met',
            measurementPeriod: 'monthly',
            lastMeasuredAt: new Date('2024-01-27').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            clientId: 3,
            contractId: 3,
            metricName: 'Bug Fix Time',
            targetValue: '< 24 hours',
            currentValue: '< 20 hours',
            status: 'met',
            measurementPeriod: 'weekly',
            lastMeasuredAt: new Date('2024-01-26').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            clientId: 4,
            contractId: 4,
            metricName: 'Support Availability',
            targetValue: '24/7 availability',
            currentValue: '24/7 availability',
            status: 'met',
            measurementPeriod: 'daily',
            lastMeasuredAt: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            clientId: 5,
            contractId: 5,
            metricName: 'Resolution Time',
            targetValue: '< 48 hours',
            currentValue: '< 45 hours',
            status: 'met',
            measurementPeriod: 'weekly',
            lastMeasuredAt: new Date('2024-01-25').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            clientId: 6,
            contractId: 6,
            metricName: 'System Performance',
            targetValue: '95% efficiency',
            currentValue: '97% efficiency',
            status: 'met',
            measurementPeriod: 'monthly',
            lastMeasuredAt: new Date('2024-01-27').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            clientId: 7,
            contractId: 7,
            metricName: 'Response Time',
            targetValue: '< 2 hours',
            currentValue: '< 2.5 hours',
            status: 'at_risk',
            measurementPeriod: 'daily',
            lastMeasuredAt: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            clientId: 8,
            contractId: null,
            metricName: 'System Uptime',
            targetValue: '99.5% uptime',
            currentValue: '99.2% uptime',
            status: 'at_risk',
            measurementPeriod: 'monthly',
            lastMeasuredAt: new Date('2024-01-27').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            clientId: 9,
            contractId: null,
            metricName: 'Bug Fix Time',
            targetValue: '< 12 hours',
            currentValue: '< 15 hours',
            status: 'breached',
            measurementPeriod: 'weekly',
            lastMeasuredAt: new Date('2024-01-26').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            clientId: 10,
            contractId: null,
            metricName: 'Resolution Time',
            targetValue: '< 24 hours',
            currentValue: '< 30 hours',
            status: 'breached',
            measurementPeriod: 'daily',
            lastMeasuredAt: new Date('2024-01-28').toISOString(),
            createdAt: new Date('2024-01-01').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
    ];

    await db.insert(slas).values(sampleSLAs);
    
    console.log('✅ SLAs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});